// app/lib/explanations.ts
// Bu dosya, 2., 3. ve 4. sınıf ders konularının müfredata uygun açıklamalarını içerir.
// Bot, bir konuyu anlatırken buradaki metinleri kaynak olarak kullanacaktır.
// BURASI HAZIR CEVAPLAR DEĞİL SADECE AI IN KULLANACAĞI KAYNAK METİNLERDİR.

export const explanations = {
  2: {
    "Türkçe": {
      "OKUMA": "Okuma, yazıları anlamak ve yeni dünyalar keşfetmek için harika bir maceradır. Bu bölümde metinlerin sırlarını nasıl çözeceğimizi ve birer anlam dedektifi olmayı öğreneceğiz!",
      "Metnin Konusu": "Metnin konusu, bir hikâyenin veya yazının kalbi gibidir. O olmadan hikâye yaşayamaz. Konuyu bulmak için kendimize şu sihirli soruyu sorarız: 'Bu yazı en çok kimden veya neden bahsediyor?'. Tıpkı bir dedektif gibi metindeki ipuçlarını takip ederek metnin konusunu bulabiliriz.",
      "Ne, Kim, Nerede?": "Bir hikayeyi tam olarak anlamak için sorduğumuz sihirli sorulardır. 'Kim?' bize hikayedeki kahramanları, 'Nerede?' olayın geçtiği yeri, 'Ne?' ise başlarından geçen macerayı anlatır. Bu soruların cevapları hikayenin haritasını çıkarır.",
      "Başlık Belirleme": "Başlık, hikâyenin kapısındaki isim tabelası gibidir. Bize içeride ne olduğunu kısaca anlatır. Konuyu bulduktan sonra, 'Bu hikâyeye en uygun isim ne olurdu?' diye düşünerek ona en yakışan başlığı bulabiliriz.",
      "Görsel Okuma": "Bazen resimler de bize bir hikâye anlatır. Resimdeki insanların yüz ifadelerine, nerede olduklarına ve ne yaptıklarına bakarak, yazıları okumadan bile orada ne olduğunu anlayabiliriz. Bu, resimlerin dilini çözmektir.",
      "Metinle İlgili Soruları Yanıtlama": "Bu, okuduğunu anlama becerisinin temelidir. Bir metni okuduktan sonra kendimize 'Hikâyenin kahramanı kimdi?' veya 'Neden üzülmüştü?' gibi sorular sormak, metni daha iyi anlamamızı sağlar.",
      "Metin Türleri": "Yazıların da farklı türleri vardır. Hikâyeler bize maceralar anlatır, şiirler duygularımızı güzel kelimelerle ifade eder. Bilgilendirici metinler ise bize hayvanlar veya gezegenler gibi konularda yeni şeyler öğretir.",
      "Hikâye Unsurları": "Her hikâye sihirli bir tarif gibidir ve 5 ana malzemesi vardır: Karakterler (Hikâyedeki kişiler kimler?), Yer (Hikâye nerede geçiyor?), Zaman (Macera ne zaman yaşanıyor?), Olay (Karakterlerin başından geçen macera nedir?) ve Ana Fikir (Yazarın bize vermek istediği ders). Bu 5 malzeme bir araya gelince harika bir hikâye ortaya çıkar!",
      "YAZMA": "Yazmak, düşüncelerimizi ve hayallerimizi kelimelerle resim yapmak gibidir. Bu bölümde, cümlelerimizi nasıl doğru ve güzel bir şekilde kuracağımızı, birer cümle mühendisi olmayı öğreneceğiz.",
      "Cümle Oluşturma": "Kelimeler, bir cümlenin legoları gibidir. Onları doğru sıraya koyarak anlamlı yapılar inşa ederiz. 'kedi ağaca tırmandı' demek yerine, 'Kedi ağaca tırmandı.' diyerek tam ve anlamlı bir cümle kurarız.",
      "Cümle Tamamlama": "Bazen cümleler yarım kalabilir ve bizim yardımımıza ihtiyaç duyarlar. 'Bugün hava çok...' gibi bir cümlenin sonunu '...güzel.' veya '...soğuk.' gibi uygun bir kelimeyle tamamlayarak ona anlam kazandırırız.",
      "Olayların Oluş Sırası": "Hikâyelerdeki olaylar, tıpkı bir trenin vagonları gibi arka arkaya sıralanır. 'Önce ne oldu, sonra ne oldu, en sonunda ne oldu?' diye düşünerek olayları doğru sıraya koymak, hikayeyi anlaşılır kılar.",
      "Büyük Harflerin Kullanımı": "Büyük harfler, kelimelerin 'özel' ve 'önemli' olduğunu gösteren bir taç gibidir! Her cümlenin ilk harfi, özel isimler (Zeynep, Ankara, Türkiye gibi), hayvanlara verdiğimiz özel isimler (Karabaş gibi) ve bayram isimleri her zaman büyük harfle başlar.",
      "Noktalama İşaretleri": "Noktalama işaretleri, cümlelere duygu ve anlam katan sihirli yardımcılardır. Nokta (.) cümlenin bittiğini, soru işareti (?) merak ettiğimizi, ünlem (!) ise heyecanımızı gösterir. Virgül (,) kısa bir mola, kesme işareti (') ise özel isimlerin korumasıdır.",
      "Harfler, Sözcükler ve Cümleler Arasında Uygun Boşluk Bırakma": "Kelimeler de nefes almak için aralarında boşluğa ihtiyaç duyar. Eğer onları birbirine çok yapıştırırsak okunamazlar. Her kelimeden sonra bir parmağını koyarak boşluk bırakabilirsin.",
      "Soru Ekinin Yazımı": "Soru sormamızı sağlayan 'mı, mi, mu, mü' ekleri biraz utangaçtır ve kendilerinden önceki kelimeye asla yapışmazlar, her zaman ayrı dururlar. 'Oyun bitti mi?' derken 'mi' ayrı yazılır.",
      "SÖZ VARLIĞI": "Kelimeler birer hazinedir! Bu bölümde kelime hazinemizi büyütecek, kelimelerin gizli anlamlarını keşfedecek ve birer kelime avcısı olacağız.",
      "Sözcüğün Anlamı": "Her kelimenin bir veya birden fazla anlamı olabilir. Bir kelimenin ne anlama geldiğini bilmiyorsak, cümlenin gelişinden tahmin etmeye çalışabilir veya bir sözlüğe bakarak anlamını öğrenebiliriz.",
      "Eş Anlamlı Sözcükler": "Eş anlamlı sözcükler, farklı kıyafetler giymiş ama aslında aynı kişi olan kelimelerdir. Yazılışları farklıdır ama anlamları tıpatıp aynıdır! Örneğin, 'öğrenci' ile 'talebe', 'hediye' ile 'armağan' gibi.",
      "Zıt Anlamlı Sözcükler": "Zıt anlamlı sözcükler, birbirine tamamen karşıt olan, sanki hiç anlaşamayan kelimelerdir. Biri 'evet' derken diğeri 'hayır' der. 'Sıcak' ile 'soğuk', 'uzun' ile 'kısa' gibi.",
      "Harf ve Hece Bilgisi": "Kelimeler hecelerden, heceler de harflerden oluşur. Ağzımızın tek bir hareketiyle söylediğimiz seslere hece deriz. Mesela 'ka-lem' derken ağzımız iki kere hareket eder, yani bu kelime iki hecelidir."
    },
    "Matematik": {
      "DOĞAL SAYILAR": "Sayıların dünyasına hoş geldin! Bu bölümde sayıları tanıyacak, onları onluk ve birliklere ayıracak, karşılaştıracak ve sıralayacağız.",
      "Nesnelerin Sayısı": "Etrafımızdaki varlıkların kaç tane olduğunu bulmaktır. Parktaki salıncakları veya tabağındaki kurabiyeleri saymak gibi!",
      "Sayıları Onluk ve Birlik Gruplara Ayırma": "Sayıların da evleri vardır! İki basamaklı sayıların iki odalı bir evi olur. Sağdaki oda 'Birlikler Evi', soldaki oda ise 'Onluklar Evi'dir. Örneğin 34 sayısında, Birlikler Evi'nde 4 tane birlik, Onluklar Evi'nde ise 3 tane onluk grubu yaşar.",
      "Nesne Sayısını Tahmin Etme": "Bir kavanozdaki bilyelere bakıp 'Sence burada kaç bilye var?' diye düşünmek, saymadan önce bir fikir yürütmektir. Sonra sayarak tahminimizin ne kadar yakın olduğunu kontrol ederiz.",
      "Basamak Adları ve Basamak Değerleri": "Bir sayıda her rakamın durduğu yerin bir adı vardır, buna basamak denir. Örneğin 47 sayısında 7'nin basamağı 'birler basamağı', 4'ünki ise 'onlar basamağı'dır. 7'nin basamak değeri 7 iken, 4'ün basamak değeri 40'tır.",
      "İleri ve Geriye Doğru Sayma": "Sayıları belirli bir ritimle ileri veya geri saymaktır. Birer, ikişer, beşer veya onar onar sayabiliriz. 10, 20, 30 diye saymak ileriye onar saymaktır.",
      "Sayı Örüntüleri": "Sayı örntüleri, gizli bir kuralı olan sihirli sayı dizileridir. Görevin, bu gizli kuralı keşfeden bir ajan olmak! Mesela 2, 4, 6, 8,... dizisinin gizli kuralı 'ikişer ikişer ileriye saymak'tır. Bir sonraki sayı 10 olmalı!",
      "Sayıları Karşılaştırma ve Sıralama": "Sayıları karşılaştırırken bize 'Aç Timsah' yardım eder. Bu timsah ağzını (< veya > işaretleri) her zaman daha büyük olan sayıya doğru açar çünkü daha çok yemek ister! 45 > 35 gibi. Sayılar eşitse timsah ağzını kapatır (=).",
      "Onluğa Yuvarlama": "Onluğa yuvarlama, bir sayının hangi onluk arkadaşına (10, 20, 30...) daha yakın olduğunu bulma oyunudur. Sayının birler basamağı 5'ten küçükse geriye, 5 veya 5'ten büyükse ileriye, bir sonraki onluğa yuvarlanır. Örneğin 23, 20'ye yuvarlanırken; 27, 30'a yuvarlanır.",
      "DOĞAL SAYILARLA TOPLAMA İŞLEMİ": "Toplama, sayıları bir araya getirerek daha büyük bir sayı elde etmektir. Bu bölümde toplama işleminin sırlarını ve problemlerini çözeceğiz.",
      "Eldeli ve Eldesiz Toplama İşlemi": "Toplama yaparken Birlikler evinde sonuç 10'u geçerse, 10 kişilik bir grup 'onluk paketi' olup yandaki Onluklar Evi'ne misafirliğe gider. İşte bu misafire 'elde var 1 onluk' deriz ve onluklarla beraber toplarız. Eğer sonuç 9'u geçmezse bu eldesiz toplamadır.",
      "DOĞAL SAYILARLA ÇIKARMA İŞLEMİ": "Çıkarma, bir sayıdan başka bir sayıyı eksiltmektir. Bu bölümde çıkarma işleminin nasıl yapıldığını ve problemlerini öğreneceğiz.",
      "Onluk Bozmadan ve Onluk Bozarak Çıkarma İşlemi": "Çıkarma yaparken birlikler yetmezse, komşu Onluklar Evi'nin kapısını çalar ve bir onluk ödünç isteriz. O bir onluk bizim eve gelince 10 tane birliğe dönüşür. Buna 'onluk bozarak çıkarma' denir. Eğer birlikler yetiyorsa, bu onluk bozmadan çıkarmadır.",
      "Zihinden Çıkarma İşlemi": "Zihinden çıkarma, sayıları aklımızda canlandırarak kağıt kalem kullanmadan eksiltme yapmaktır. Örneğin 50'den 20'yi çıkarmak için onlukları sayarak 40, 30 diye geri gidebiliriz.",
      "Verilmeyen Toplananı Bulma": "Bir toplama işleminde sayılardan biri eksikse, onu bulma oyunudur. 5 + ? = 8 işleminde, eksik sayıyı bulmak için toplamdan (8) verilen sayıyı (5) çıkarırız. Cevap 3'tür!",
      "Sayıların Toplamını Tahmin Etme": "Sayıları en yakın onluğa yuvarlayarak gerçek sonuca yakın bir cevap bulmaktır. Örneğin 48 + 31 işleminin sonucunu tahmin etmek için 50 + 30 = 80 diyebiliriz.",
      "Zihinden Toplama İşlemi": "Zihinden toplama, aklımızla süper hızlı hesap yapma gücüdür! Mesela 38+7 işlemi için, 38'e 7'den 2 alıp vererek onu 40 yaparız. Geriye 5 kalır. 40+5=45. Ne kadar kolay!",
      "Toplama İşlemiyle Problem Çözelim": "Günlük hayattaki sorunları toplama işlemi kullanarak çözmektir. 'Ali'nin 5 misketi vardı, Ayşe 3 misket daha verdi. Ali'nin kaç misketi oldu?' sorusu bir toplama problemidir.",
      "Çıkarma İşleminin Sonucunu Tahmin Etme": "Tıpkı toplamada olduğu gibi, sayıları en yakın onluğa yuvarlayarak çıkarma işleminin sonucunu tahmin etmektir. 79 - 22 işlemini tahmin etmek için 80 - 20 = 60 diyebiliriz.",
      "Toplama ve Çıkarma İşlemleri Arasındaki İlişki": "Toplama ve çıkarma birbirinin tersidir, sanki zıt yönlere giden iki arkadaş gibidirler. 5 + 3 = 8 ise, 8 - 3 = 5'tir. Birini biliyorsak diğerini kolayca bulabiliriz.",
      "Eşit İşareti": "Eşittir (=) işareti, terazinin iki kefesinin dengede olması gibidir. İşaretin solundaki işlemin sonucu ile sağındaki işlemin sonucu birbirinin aynısıdır. Örneğin, 4 + 5 = 9.",
      "Çıkarma İşlemiyle Problem Çözelim": "Günlük hayattaki sorunları çıkarma işlemi kullanarak çözmektir. 'Sepette 10 elma vardı, 4 tanesini yedik. Sepette kaç elma kaldı?' sorusu bir çıkarma problemidir.",
      "SIVI ÖLÇME": "Sıvıları, yani su, süt, meyve suyu gibi şeyleri ne kadar olduklarını anlamak için ölçeriz. Bunun için litre gibi ölçü birimlerini kullanırız.",
      "Sıvı Ölçme": "Sıvıları ölçmek için kullandığımız standart birim litredir. Bir sürahinin ne kadar su aldığını veya bir şişede ne kadar süt olduğunu litre ile ifade ederiz.",
      "GEOMETRİK CİSİMLER VE ŞEKİLLER": "Etrafımızdaki nesnelerin şekillerini ve yapılarını inceleyeceğiz. Bazıları düz, bazıları ise üç boyutludur!",
      "Şekillerin Kenar ve Köşe Sayıları": "Geometrik şekillerin kenarları ve köşeleri vardır. Karenin 4 eşit kenarı ve 4 köşesi, üçgenin ise 3 kenarı ve 3 köşesi bulunur.",
      "Süslemeler": "Farklı geometrik şekilleri belirli bir kurala göre tekrar tekrar kullanarak güzel desenler ve süslemeler oluşturmaktır.",
      "Geometrik Cisimlerin Modelleri": "Küp, silindir, küre gibi üç boyutlu cisimleri karton veya oyun hamuru gibi malzemelerle oluşturarak onları daha iyi tanımaktır.",
      "Geometrik Cisimler": "Şekiller (kare, üçgen, daire) düzdür, kağıda çizebiliriz. Cisimler (küp, küre, silindir) ise üç boyutludur, elimize alabiliriz. Bir kutu küpe, bir top küreye örnektir.",
      "UZAMSAL İLİŞKİLER": "Nesnelerin birbirine göre nerede durduğunu (içinde, dışında, altında, üstünde) ve simetriyi anlamaktır.",
      "Uzamsal İlişkiler": "Bir nesnenin başka bir nesneye göre konumunu belirtir. 'Kedi masanın altında' veya 'kitap kutunun içinde' gibi ifadeler uzamsal ilişkileri anlatır.",
      "Simetrik Şekiller": "Bir şekli ortadan ikiye katladığımızda iki tarafı da tam olarak üst üste geliyorsa, o şekil simetriktir. Bir kelebeğin kanatları veya bir kalp şekli simetriye güzel bir örnektir.",
      "GEOMETRİK ÖRÜNTÜLER": "Şekillerin veya cisimlerin belirli bir kurala göre sıralanmasıdır. Tıpkı bir şarkının ritmi gibi!",
      "Geometrik Örüntüler": "Şekillerin belirli bir kurala göre tekrarlanmasıdır. Örneğin, 'kare, daire, üçgen, kare, daire, üçgen...' bir geometrik örüntüdür. Kural, şekillerin sırayla tekrar etmesidir.",
      "DOĞAL SAYILARLA ÇARPMA İŞLEMİ": "Çarpma, toplamanın hızlı ve kısa yoludur. Tekrar eden sayıları toplamak yerine çarparak sonuca daha kolay ulaşırız.",
      "Toplama İşleminden Çarpma İşlemine": "Tekrar eden toplamaları çarpma işlemine dönüştürmektir. 5 + 5 + 5 demek yerine, '3 tane 5' yani '3 x 5' yazabiliriz. İkisi de aynı sonucu, yani 15'i verir.",
      "Çarpma İşlemi": "Çarpma, toplamanın hızlı ve havalı yoludur. 4 tane 5'i toplamak yerine (5+5+5+5), '4 kere 5' diyerek aynı sonuca çok daha hızlı ulaşırız. Çarpma, tekrar eden toplamaların kısayoludur.",
      "Çarpma İşlemiyle Problem Çözelim": "Günlük hayattaki sorunları çarpma işlemiyle çözmektir. 'Her birinde 5 şeker olan 4 paket aldım. Toplam kaç şekerim oldu?' sorusu bir çarpma problemidir.",
      "DOĞAL SAYILARLA BÖLME İŞLEMİ": "Bölme, bir bütünü eşit parçalara ayırmak veya paylaştırmaktır. Adaletli bir paylaşım oyunudur!",
      "Çıkarma İşleminden Bölme İşlemine": "Bir sayıdan aynı sayıyı tekrar tekrar çıkarmanın kısa yoludur. 12'den kaç tane 3 çıkarabileceğimizi bulmak, 12'yi 3'e bölmekle aynı şeydir. Cevap 4'tür.",
      "Bölme İşlemi": "Bölme işlemi, en adil paylaştırma oyunudur! Elimizdeki 12 kurabiyeyi 3 arkadaşımıza eşit olarak paylaştırmaktır. Her birine kaç kurabiye düşeceğini bulmaya bölme denir. Bölme, aynı zamanda çarpmanın tersidir.",
      "KESİRLER": "Bir bütünün eş parçalarını ifade etmenin yoludur. Bir pastanın dilimleri gibi!",
      "Kesirler": "Bir bütün elmayı iki eş parçaya böldüğümüzde, her bir parçaya 'yarım' (1/2) deriz. Dört eş parçaya böldüğümüzde ise her birine 'çeyrek' (1/4) deriz. Kesirler, bir bütünün eş parçalarını gösterir.",
      "ZAMAN ÖLÇME": "Zamanı saat, gün, hafta gibi birimlerle ölçerek günlük hayatımızı planlamayı öğreniriz.",
      "Zaman Ölçme": "Model bir saat üzerinde yelkovan ve akrebin görevleri anlatılır. Tam, yarım ve çeyrek saatler öğretilir. Günlük rutinler (sabah 7'de kalkmak, akşam 9'da uyumak) saat üzerinde gösterilir.",
      "Zaman Ölçü Birimleriyle İlgili Problemler": "Zaman birimlerini kullanarak problem çözmektir. 'Saat 3'te başlayan bir film 2 saat sürerse, film bittiğinde saat kaç olur?' gibi soruları cevaplarız.",
      "PARALARIMIZ": "Günlük hayatta kullandığımız paraları tanıyacak ve onlarla basit alışveriş problemleri çözeceğiz.",
      "Paralarımız": "Oyuncak paralarla bir market köşesi oluşturulur. Ürünlere fiyat etiketleri yapıştırılır. Çocuk, alışveriş yaparak para üstü alıp verme pratiği yapar.",
      "Paralarımızla İlgili Problem Çözelim": "Paraları kullanarak alışveriş problemleri çözmektir. 'Cebimde 10 TL var. 7 TL'ye bir kitap alırsam, geriye kaç liram kalır?' gibi.",
      "VERİ TOPLAMA VE DEĞERLENDİRME": "Bilgileri toplayıp tablolar ve grafiklerle daha anlaşılır hale getirmeyi öğreneceğiz.",
      "Şekil ve Nesne Grafiği": "Topladığımız bilgileri şekil veya nesneler kullanarak göstermektir. 'Sınıftaki en sevilen meyveler' anketinde, her meyve için bir elma resmi çizerek bir grafik oluşturabiliriz. En çok elma resmi olan, en sevilen meyvedir.",
      "UZUNLUK ÖLÇME": "Nesnelerin ne kadar uzun olduğunu standart ölçü birimleri olan santimetre ve metre ile ölçmeyi öğreneceğiz.",
      "Uzunluk Ölçme": "Nesnelerin uzunluğunu ölçmek için metre ve santimetre kullanırız. Bir kalemin boyunu santimetre ile ölçerken, bir odanın uzunluğunu metre ile ölçmek daha kolaydır.",
      "Uzunlukları Ölçmeyle İlgili Problem Çözelim": "Uzunluk birimlerini kullanarak problem çözmektir. '80 cm uzunluğundaki bir kurdelenin 20 cm'sini kesersem, geriye kaç cm kurdele kalır?' gibi.",
      "TARTMA": "Nesnelerin ne kadar ağır olduğunu kilogram ve gram ile ölçmeyi öğreneceğiz.",
      "Tartma": "Bir nesnenin ağırlığını ölçmek için kilogram ve gram kullanırız. Bir elmanın ağırlığını gram ile ölçerken, bir çuval patatesin ağırlığını kilogram ile ölçeriz."
    },
    "Hayat Bilgisi": {
      "OKULUMUZDA HAYAT": "Okul, sadece derslerin olduğu bir yer değil, aynı zamanda arkadaşlarımızla birlikte büyüdüğümüz, kuralları ve beraber yaşamayı öğrendiğimiz bir yerdir.",
      "Özelliklerim": "Her birimizin bizi biz yapan farklı özellikleri vardır. Kimimiz iyi resim çizer, kimimiz hızlı koşar. Bu özellikler bizi özel kılar.",
      "Bireysel Farklılıklar": "Sınıfımız ve dünyamız rengarenk bir çiçek bahçesi gibidir. Her birimiz farklı bir çiçeğiz. Bu farklılıklarımız aslında bizim süper güçlerimizdir! Bu farklılıklar sayesinde toplumumuz daha güzel bir yer olur.",
      "Planlı Olalım": "Günü planlamak, o gün için bir hazine haritası çizmeye benzer. Haritamızda 'Ders Çalışma Adası', 'Oyun Oynama Ormanı' ve 'Uyku Dağı' gibi yerler olur. Plan yapmak, hem işlerimizi zamanında bitirmemizi hem de eğlenceye vakit ayırmamızı sağlar.",
      "Karar Alma Süreçleri": "Aile veya grup içinde bir karar alınırken herkesin fikrini söylemesi önemlidir. Senin de fikirlerin çok değerli! Fikirlerimizi saygıyla söylemek ve başkalarını dinlemek, en doğru kararı birlikte almamızı sağlar.",
      "Okulum": "Okulumuzun bölümlerini ve çalışanlarını tanımak, okulumuzu daha iyi tanımamızı ve sevmemizi sağlar. Müdür odası, kütüphane, öğretmenler odası gibi yerlerin görevlerini öğreniriz.",
      "Özen Gösterelim": "Okuldaki ve evdeki eşyaları özenli kullanmak bir sorumluluktur. Sıramızı temiz tutmak veya kitaptaki sayfaları yırtmamak, hem kendimize hem de başkalarına saygı göstermektir.",
      "Grup Çalışma Kuralları": "Grup çalışması yaparken herkesin bir görevi olur. Birbirimizi dinlemek, fikirlerimize saygı göstermek ve iş bölümü yapmak, çalışmamızı daha başarılı ve eğlenceli hale getirir.",
      "İletişim Kuralım": "İnsanlarla konuşurken nezaket ifadeleri ('lütfen', 'teşekkür ederim' gibi) kullanmak, göz teması kurmak ve gülümsemek, sağlıklı bir iletişim için çok önemlidir.",
      "Oyun Kuralları": "Oyunların daha eğlenceli ve adil olması için kuralları vardır. Kurallara uymak, oyundaki herkesin keyif almasını sağlar. Mızıkçılık yapmak ise oyunun tadını kaçırır.",
      "Paramı Doğru Harcıyorum": "Paramızı harcarken isteklerimiz ve ihtiyaçlarımız arasındaki farkı bilmeliyiz. Paramızı önce ihtiyaçlarımız için kullanmak, bilinçli bir tüketici olmanın ilk adımıdır.",
      "EVİMİZDE HAYAT": "Evimiz, ailemizle birlikte yaşadığımız, sevgi ve güven dolu en özel yerimizdir. Evde de görevlerimiz ve sorumluluklarımız vardır.",
      "Yakın Akrabalarımız": "Ailemiz sadece anne, baba ve kardeşlerden oluşmaz. Dede, nine, amca, hala, teyze, dayı ve kuzenler de bizim yakın akrabalarımızdır ve büyük ailemizin bir parçasıdır.",
      "Adresimizi Öğrenelim": "Acil bir durumda veya bir yere davetiye göndermek için ev adresimizi bilmek çok önemlidir. Adresimiz; mahalle, sokak, apartman adı, numara, ilçe ve şehir bilgilerini içerir.",
      "Benim Görev ve Sorumluluklarım": "Evde ve okulda hepimizin görevleri vardır. Odanı toplamak, okul çantanı hazırlamak, evdeki hayvan dostumuzu beslemek gibi. Sorumluluklarımızı yerine getirmek, hem kendimize hem de ailemize yardımcı olmaktır ve bizi büyütür.",
      "Ailemizde Karar Alma Süreçleri": "Evle ilgili bir karar alınırken (örneğin tatile nereye gidileceği), ailedeki herkesin fikrini söylemesi önemlidir. Fikirlerimizi saygıyla paylaşmak, en doğru kararı birlikte almamızı sağlar.",
      "Kaynakları Bilinçli Tüketmeliyiz": "Dişini fırçalarken suyu kapatmak, odadan çıkarken ışığı söndürmek, tabağımıza yiyeceğimiz kadar yemek almak... Bunlar, dünyamızın kaynaklarını (su, elektrik, yiyecek) korumak için yapabileceğimiz kahramanlıklardır.",
      "Duyarlı Olalım": "Çevremizdeki insanlara, hayvanlara ve bitkilere karşı duyarlı olmak önemlidir. Yardıma ihtiyacı olan bir arkadaşımıza yardım etmek veya bir sokak hayvanına su vermek, duyarlı bir davranış örneğidir.",
      "Planlı İşlerim": "Tıpkı okulda olduğu gibi evdeki zamanımızı da planlamak, hem ödevlerimizi yapmamıza hem de oyun oynamaya ve dinlenmeye yeterli vakit ayırmamıza yardımcı olur.",
      "İstek ve İhtiyaçlarımız": "İhtiyaçlar, yaşamak için zorunlu olan şeylerdir: su, yemek, barınma gibi. İstekler ise bizi mutlu eden ama olmasa da yaşayabileceğimiz şeylerdir: yeni bir oyuncak, çikolata gibi. Paramızı harcarken önce ihtiyaçlarımızı düşünmeliyiz.",
      "SAĞLIKLI HAYAT": "Sağlıklı olmak, sadece hasta olmamak değil, aynı zamanda bedenimize ve ruhumuza iyi bakmaktır. Doğru beslenme ve temizlik bunun temelidir.",
      "Sağlıklı Büyüme ve Gelişme": "Vücudumuzun sağlıklı bir şekilde büyüyüp gelişmesi için üç şeye ihtiyacı var: İyi yakıt (dengeli beslenme), hareket (spor ve oyun) ve dinlenme (yeterli uyku). Tıpkı bir arabanın gitmek için benzine ihtiyacı olduğu gibi!",
      "Dengeli Beslenme": "Her çeşit besinden yeteri kadar yemektir. Tabağımızda sebze, meyve, et veya süt ürünleri gibi farklı yiyecek gruplarından yiyeceklerin olması, dengeli beslendiğimiz anlamına gelir.",
      "Görgü Kuralları": "Yemek yerken ağzımızı şapırdatmamak, konuşurken ağzımızda yemek olmaması, 'afiyet olsun' demek gibi kurallar, başkalarıyla birlikte yemek yemenin adabıdır.",
      "Çevremizi Temiz Tutalım": "Yaşadığımız çevreyi (ev, okul, sokak) temiz tutmak hem bizim sağlığımız hem de başkalarının sağlığı için önemlidir. Çöpleri çöp kutusuna atmak bu işin ilk adımıdır.",
      "Sağlıkla İlgili Kurumlar ve Meslekler": "Hastalandığımızda gittiğimiz hastane, aile sağlığı merkezi gibi yerler sağlık kurumlarıdır. Doktor, hemşire, eczacı gibi meslekler ise sağlığımız için çalışan kişilerdir.",
      "Mevsimine Uygun Sebze ve Meyve": "Her sebze ve meyvenin en lezzetli ve en sağlıklı olduğu bir mevsim vardır. Örneğin, karpuzu yazın, portakalı ise kışın yemek en doğrusudur.",
      "Mevsime Göre Giyinelim": "Vücudumuzu hastalıklardan korumak için hava durumuna ve mevsime uygun giyinmeliyiz. Yazın ince ve açık renkli, kışın ise kalın ve koyu renkli kıyafetler tercih ederiz.",
      "GÜVENLİ HAYAT": "Günlük hayatta kendimizi tehlikelerden nasıl koruyacağımızı öğrenmektir. Trafik kuralları ve acil durumlar bu konunun en önemli parçalarıdır.",
      "Ulaşım Türleri ve Araçları": "Bir yerden bir yere gitmek için kullandığımız yollara ulaşım türü (kara yolu, demir yolu, hava yolu, deniz yolu), bu yollarda giden taşıtlara ise ulaşım aracı (otomobil, tren, uçak, gemi) denir.",
      "Ulaşım Araçlarıyla Yolculuk": "Toplu taşıma araçlarında (otobüs, metro gibi) yaşlılara, hamilelere ve engellilere yer vermek, yüksek sesle konuşmamak gibi kurallara uymak önemlidir.",
      "Trafikte Yardımlaşalım": "Trafikte birbirimize karşı saygılı ve yardımsever olmalıyız. Görme engelli birinin karşıya geçmesine yardım etmek veya yol tarifi sormak, trafikte yardımlaşmaya örnektir.",
      "Acil Durumlar": "Yangın, deprem gibi beklenmedik durumlarda sakin kalmalı ve tek bir sihirli numarayı bilmeliyiz: 112. Bu numarayı aradığında, sana yardım edecek polis, itfaiye veya ambulans hemen yola çıkar.",
      "Teknolojik Araç ve Gereçler": "Teknolojiyi kullanırken dikkatli olmalıyız. Bilgisayar veya tablet başında çok uzun süre kalmamak, internette tanımadığımız kişilerle konuşmamak gibi kurallara uymak güvenliğimiz için önemlidir.",
      "Oyun Oynarken Dikkat Edelim": "Oyun alanlarımızı (park, okul bahçesi) güvenli bir şekilde kullanmalıyız. Kırık salıncaklara binmemek veya inşaat alanlarında oynamamak gibi tehlikelerden uzak durmalıyız.",
      "ÜLKEMİZDE HAYAT": "Yaşadığımız ülke olan Türkiye'yi, bayrağımızı, milli bayramlarımızı ve kültürel zenginliklerimizi tanıyacağız.",
      "Ülkemizin Yeri": "Biz, Türkiye adında çok güzel bir ülkede yaşıyoruz. Dünya haritasına baktığımızda ülkemizin yerini görebiliriz. Üç tarafı denizlerle çevrilidir.",
      "Bayrağımız ve İstiklal Marşımız": "Bizim bayrağımız, kırmızı rengi ve üzerindeki ay ve yıldızıyla dünyadaki en güzel bayraklardan biridir. O, bizim bağımsızlığımızın sembolüdür. İstiklal Marşımız da bayrağımız gibi çok değerlidir, onu duyduğumuzda saygıyla ayağa kalkarız.",
      "Atatürk de Çocuktu": "Ülkemizi kuran liderimiz Mustafa Kemal Atatürk de bir zamanlar bizim gibi bir çocuktu. O da oyunlar oynadı, okula gitti ve hayaller kurdu.",
      "Millî Bayramlarımız": "Millet olarak hep birlikte kutladığımız özel günlerdir. 23 Nisan Ulusal Egemenlik ve Çocuk Bayramı, 19 Mayıs Atatürk'ü Anma, Gençlik ve Spor Bayramı, 30 Ağustos Zafer Bayramı ve 29 Ekim Cumhuriyet Bayramı bizim milli bayramlarımızdır.",
      "Dinî Bayramlarımız": "Müslümanların kutladığı iki büyük bayram vardır: Ramazan Bayramı ve Kurban Bayramı. Bu bayramlarda aile büyüklerimizi ziyaret eder, onlarla bayramlaşırız.",
      "Kültürel Miras Ögeleri": "Geçmişten günümüze gelen ve bizi biz yapan değerlerdir. Geleneksel yemeklerimiz (mantı gibi), halk oyunlarımız (horon gibi), el sanatlarımız (çinicilik gibi) kültürel mirasımıza örnektir.",
      "Farklı Kültür ve Yaşam Şekilleri": "Ülkemizde veya dünyada bizden farklı geleneklere ve yaşam tarzlarına sahip insanlar yaşayabilir. Bu farklılıklara saygı duymak çok önemlidir.",
      "Üretim Faaliyetleri": "İnsanların ihtiyaçlarını karşılamak için yapılan işlerdir. Çiftçilerin buğday yetiştirmesi (tarım), fabrikaların araba yapması (sanayi), doktorların hastaları iyileştirmesi (hizmet) birer üretim faaliyetidir.",
      "DOĞADA HAYAT": "Çevremizdeki canlıları, doğa olaylarını ve gezegenimizi daha yakından tanıyacağız. Doğayı korumanın önemini öğreneceğiz.",
      "Bitki ve Hayvanlar": "Doğa, bitkiler ve hayvanlarla doludur. Yakın çevremizdeki ağaçları, çiçekleri, kedileri, köpekleri ve kuşları gözlemleyerek onların yaşamları hakkında bilgi edinebiliriz.",
      "Hayvanları Sevelim, Bitki Yetiştirelim": "Hayvanlara ve bitkilere sevgi ve şefkat göstermek bir insanlık görevidir. Bir saksıya çiçek ekmek veya sokaktaki bir kediye su vermek, doğa sevgisinin bir göstergesidir.",
      "Doğal Unsurlar": "Doğada insan eliyle yapılmamış, kendiliğinden var olan şeylerdir. Dağlar, denizler, nehirler, ormanlar, ovalar birer doğal unsurdur.",
      "Geri Dönüşüm": "Geri dönüşüm, çöplere sihirli bir değnekle dokunup onlara yeni bir hayat vermektir! Kullandığımız kağıt, plastik ve cam gibi atıkları doğru kutulara atarak dünyamızı temiz tutabilir ve kaynaklarımızı koruyabiliriz.",
      "Doğa Olayları": "Doğanın kendi döngüsü içinde gerçekleşen olaylardır. Yağmur, kar, rüzgar, sis ve gökkuşağı birer doğa olayıdır.",
      "Doğal Afetler ve Alınacak Önlemler": "Doğa olayları bazen çok şiddetli olup deprem, sel, fırtına gibi tehlikeli durumlara yol açabilir. Bunlara doğal afet denir. Deprem çantası hazırlamak gibi önlemler alarak kendimizi koruyabiliriz.",
      "Yönler": "Yönler, bir yeri bulmamıza yarayan gizli işaretlerdir. Dört ana yön vardır: Doğu, Batı, Kuzey ve Güney. Güneş her sabah Doğu'dan doğar, akşam ise Batı'dan batar.",
      "Dünya'nın Şekli ve Hareketleri": "Gezegenimiz Dünya, tıpkı bir top gibi küre şeklindedir. Dünyamız hem kendi etrafında (gece-gündüz oluşur) hem de Güneş'in etrafında (mevsimler oluşur) sürekli dönen dev bir topaç gibidir."
    },
    "İngilizce": {
      "WORDS": "İngilizcede kelimeleri ve anlamlarını öğrenmek, yeni bir dil konuşmanın ilk adımıdır.",
      "Telling people what we know (Vocabulary)": "Basit nesnelerin ve kavramların İngilizce karşılıklarını öğrenmektir. Örneğin 'book' (kitap), 'cat' (kedi), 'red' (kırmızı) gibi.",
      "FRIENDS": "Arkadaşlarımızla nasıl tanışacağımızı ve selamlaşacağımızı öğreneceğiz.",
      "Asking someone’s name (What's your name?)": "Biriyle tanışırken şu diyaloğu kullanırız:\nA: Hello! What's your name? (Merhaba! Senin adın ne?)\nB: My name is Ayşe. (Benim adım Ayşe.)",
      "Greeting and meeting people - 1 (Greetings)": "Selamlaşmak için 'Hello!' veya 'Hi!' deriz. Vedalaşırken ise 'Goodbye!' veya 'Bye!' kullanırız.",
      "Greeting and meeting people - 2 (How are you?)": "Birinin nasıl olduğunu sormak için 'How are you?' deriz. Cevap olarak 'I'm fine, thank you.' (İyiyim, teşekkür ederim) diyebiliriz.",
      "IN THE CLASSROOM": "Sınıf içinde kullanılan basit İngilizce komutları ve ifadeleri öğreneceğiz.",
      "Giving simple directions (Please)": "Bir şey isterken cümlenin sonuna 'please' (lütfen) eklemek, ifademizi daha kibar hale getirir. 'Open the door, please.' gibi.",
      "Giving and responding to simple instructions - 1 (Imperatives 1)": "Sınıfta bazen basit komutlar duyarız:\nStand up, please. (Lütfen ayağa kalk.)\nSit down, please. (Lütfen otur.)\nOpen your book. (Kitabını aç.)",
      "Giving and responding to simple instructions - 2 (Imperatives 2)": "Sınıf içindeki diğer komutları öğrenmektir: 'Be quiet' (Sessiz ol), 'Listen' (Dinle), 'Look' (Bak) gibi.",
      "Asking for clarification (I'm sorry)": "Bir şeyi anlamadığımızda 'I'm sorry, can you repeat that?' (Üzgünüm, tekrar edebilir misiniz?) diyerek tekrar edilmesini isteyebiliriz.",
      "Expressing and responding to thanks (Thank you)": "Birisi bize yardım ettiğinde 'Thank you' (Teşekkür ederim) deriz. Karşılığında ise 'You're welcome' (Rica ederim) denir.",
      "NUMBERS": "İngilizcede sayıları saymayı ve sormayı öğreneceğiz.",
      "Naming numbers (Numbers)": "Sayıların İngilizce karşılıklarını öğrenmektir. Örneğin: 1 (one), 2 (two), 3 (three), 10 (ten) gibi.",
      "Naming classroom objects (Vocabulary)": "Sınıftaki nesnelerin İngilizce adlarını öğrenmektir: 'book' (kitap), 'pencil' (kurşun kalem), 'table' (masa), 'chair' (sandalye) gibi.",
      "Expressing quantity - 1 (How many …?)": "Bir şeyin miktarını sormak için 'How many...?' kalıbını kullanırız. 'How many pencils?' (Kaç tane kalem var?).",
      "Expressing quantity - 2 (There is / There are)": "Bir şeyin varlığını belirtmek için kullanırız. Tek bir nesne için 'There is a book' (Bir kitap var), birden fazla nesne için 'There are three books' (Üç kitap var) deriz.",
      "Making simple inquiries (How old are you?)": "Birinin yaşını sormak için 'How old are you?' (Kaç yaşındasın?) deriz. Cevap olarak 'I am 8 years old' (8 yaşındayım) denir.",
      "COLOURS": "Renklerin İngilizce isimlerini ve onlarla ilgili cümleler kurmayı öğreneceğiz.",
      "Naming colours - 1 (Colours - 1)": "Temel renkleri öğrenmektir: 'red' (kırmızı), 'blue' (mavi), 'yellow' (sarı), 'green' (yeşil) gibi.",
      "Naming colours - 2 (Colours - 2)": "Diğer renkleri öğrenmektir: 'black' (siyah), 'white' (beyaz), 'orange' (turuncu), 'purple' (mor) gibi.",
      "Making simple inquiries (What colour is it?)": "Bir nesnenin rengini sormak için 'What colour is it?' (Bu ne renk?) deriz. Cevap olarak 'It is red' (O kırmızı) denir.",
      "Expressing likes and dislikes (Like / Don't like)": "Sevdiğimiz ve sevmediğimiz şeyleri belirtmek için kullanırız. 'I like blue' (Maviyi severim). 'I don't like pink' (Pembeyi sevmem).",
      "AT THE PLAYGROUND": "Oyun parkında arkadaşlarımızla İngilizce konuşarak oyunlar oynamayı öğreneceğiz.",
      "Making simple inquiries (Do you …?)": "Birinin bir şeyi sevip sevmediğini sormak için 'Do you...?' kalıbını kullanırız. 'Do you like to swing?' (Sallanmayı sever misin?).",
      "Making simple suggestions (Let's …)": "Birlikte bir şey yapmayı teklif etmek için 'Let's...' kalıbını kullanırız. 'Let's play football!' (Hadi futbol oynayalım!).",
      "BODY PARTS": "Vücudumuzun bölümlerinin İngilizce isimlerini şarkılar ve oyunlarla öğreneceğiz.",
      "Talking about possessions (My / your)": "Sahiplik belirtmek için kullanırız. 'This is my head' (Bu benim başım). 'This is your hand' (Bu senin elin).",
      "Making simple inquiries (What is this?)": "Bir nesnenin ne olduğunu sormak için 'What is this?' (Bu ne?) deriz. Cevap olarak 'This is a nose' (Bu bir burun) denir.",
      "Telling someone what to do (Imperatives)": "Vücudumuzla ilgili komutlar vermektir: 'Touch your head' (Başına dokun), 'Clap your hands' (Ellerini çırp) gibi.",
      "PETS": "Evcil hayvanların isimlerini ve nerede olduklarını söylemeyi öğreneceğiz.",
      "Talking about locations of things (Prepositions)": "Nesnelerin yerini belirtmek için 'in' (içinde), 'on' (üstünde), 'under' (altında) gibi edatları kullanırız. 'The cat is on the table' (Kedi masanın üstünde).",
      "Making simple inquiries (Where is …?)": "Bir şeyin nerede olduğunu sormak için 'Where is...?' kalıbını kullanırız. 'Where is the dog?' (Köpek nerede?).",
      "FRUITS": "Meyvelerin İngilizce isimlerini ve onları sevip sevmediğimizi söylemeyi öğreneceğiz.",
      "Expressing likes and dislikes - 1 (Vocabulary)": "Meyvelerin adlarını öğrenmektir: 'apple' (elma), 'banana' (muz), 'orange' (portakal), 'strawberry' (çilek) gibi.",
      "Expressing likes and dislikes - 2 (Do you …?)": "Birinin bir meyveyi sevip sevmediğini sormaktır. 'Do you like apples?' (Elma sever misin?). Cevap: 'Yes, I do' (Evet, severim) veya 'No, I don't' (Hayır, sevmem).",
      "Telling someone what to do (Imperatives - 1)": "Meyvelerle ilgili basit komutlar vermektir. 'Eat the apple' (Elmayı ye). 'Wash the banana' (Muzu yıka).",
      "Giving and responding to simple instructions (Imperatives - 2)": "Meyvelerle ilgili yönergeler vermektir. 'Give me an orange, please' (Bana bir portakal ver, lütfen).",
      "ANIMALS": "Hayvanların isimlerini ve yapabildikleri şeyleri söylemeyi öğreneceğiz.",
      "Expressing abilities (Can / Can't)": "Yapabildiğimiz ve yapamadığımız şeyleri belirtmek için 'can' ve 'can't' kullanırız. 'A bird can fly' (Bir kuş uçabilir). 'A fish can't walk' (Bir balık yürüyemez).",
      "Making simple inquiries (Can you …?)": "Birinin bir şeyi yapıp yapamadığını sormak için 'Can you...?' kalıbını kullanırız. 'Can you swim?' (Yüzebilir misin?)."
    }
  },
  3: {
    "Türkçe": {
      "Harfler Ve Özellikleri": "Türkçede 29 harf vardır. Bu harflerin bazıları 'sesli' (a, e, ı, i, o, ö, u, ü) bazıları ise 'sessiz'dir. Sesli harfler olmadan kelime oluşturamayız.",
      "Anlam Bilgisi": "Kelimelerin anlamlarını öğrenmektir. Eş anlamlı, zıt anlamlı ve eş sesli kelimeler bu konunun içindedir ve kelime hazinemizi zenginleştirir.",
      "Adlar (İsimler)": "Adlar (isimler), çevremizdeki varlıkları, kişileri ve yerleri tanımamızı sağlayan kelimelerdir. Her şeyin bir adı vardır: 'kedi', 'masa', 'Ayşe', 'park' gibi.",
      "Ön Adlar (Sıfat)": "Sıfatlar (ön adlar), isimlerin önüne gelerek onların rengini, durumunu, şeklini veya sayısını anlatan kelimelerdir. Varlıkları süslerler! 'Kırmızı araba' veya 'üç elma' cümlelerindeki 'kırmızı' ve 'üç' kelimeleri birer sıfattır.",
      "Adıllar (Zamir)": "Zamirler (adıllar), isimlerin yerine geçen kelimelerdir. 'Ali okula gitti' yerine 'O okula gitti' dediğimizde, 'O' kelimesi Ali'nin yerini tutan bir zamirdir. Ben, sen, o, biz, siz, onlar en çok kullandığımız zamirlerdir.",
      "Eylem (Fiil)": "Eylemler (fiiller), bir iş, oluş veya hareket bildiren kelimelerdir. Cümlenin motoru gibidirler, onu hareket ettirirler! 'Koşmak', 'zıplamak', 'uyumak', 'okumak' birer eylemdir.",
      "Eylem Kipleri": "Eylemin ne zaman yapıldığını veya nasıl yapılması gerektiğini bildiren eklerdir. Haber kipleri ve dilek kipleri olarak ikiye ayrılır.",
      "Haber Kipleri": "Eylemin ne zaman yapıldığını bildiren zaman ekleridir. Geçmiş zaman (-di), şimdiki zaman (-yor), gelecek zaman (-ecek) ve geniş zaman (-r) olmak üzere dörde ayrılır.",
      "Yapılarına Göre Eylemler": "Eylemlerin basit, türemiş veya birleşik yapıda olmasını inceler. 'Gel-' basit bir eylemken, 'başla-' (baştan gelir) türemiş bir eylemdir.",
      "Cümle Çeşitleri Ve Cümle Yapısı": "Cümlelerin anlamlarına (olumlu, olumsuz, soru) ve yapılarına göre nasıl sınıflandırıldığını öğreniriz. 'Okula gittim' olumlu bir cümleyken, 'Okula gitmedim' olumsuz bir cümledir.",
      "Büyük Harflerin Kullanıldığı Yerler": "Büyük harflerin sadece cümle başında ve özel isimlerde değil, aynı zamanda adreslerde, kurum adlarında ve kitap başlıklarında da kullanıldığını öğreniriz.",
      "Noktalama İşaretleri": "Yazılarımızı daha anlaşılır kılmak için kullandığımız işaretlerdir. Nokta, virgül, soru işareti, ünlem, kesme işareti gibi işaretlerin görevlerini detaylı olarak öğreniriz.",
      "Metin Türleri Ve Metinler": "Yazıların amaçlarına göre farklı türleri olduğunu öğreniriz. Hikaye, şiir, mektup, anı gibi metin türlerinin özelliklerini ve nasıl yazıldıklarını inceleriz."
    },
    "Matematik": {
      "Doğal Sayılar": "Üç basamaklı doğal sayıları okumayı, yazmayı, basamak değerlerini bulmayı, karşılaştırmayı ve en yakın onluğa/yüzlüğe yuvarlamayı öğreniriz.",
      "Doğal Sayılarla Toplama İşlemi": "Üç basamaklı sayılarla eldeli toplama işlemi yapmayı ve toplama işleminin sonucunu tahmin etmeyi öğreniriz.",
      "Doğal Sayılarla Çıkarma İşlemi": "Üç basamaklı sayılarla onluk ve yüzlük bozarak çıkarma işlemi yapmayı ve zihinden çıkarma stratejilerini öğreniriz.",
      "Veri Toplama ve Değerlendirme": "Bilgileri toplamak için anket gibi yöntemler kullanmayı ve topladığımız bilgileri çetele ve sıklık tablolarıyla göstermeyi öğreniriz.",
      "Doğal Sayılarla Çarpma İşlemi": "Çarpım tablosunu öğrenir, eldeli çarpma işlemi yapar ve çarpma işlemini problem çözmede kullanırız.",
      "Doğal Sayılarla Bölme İşlemi": "Bölme işleminin terimlerini (bölünen, bölen, bölüm, kalan) öğrenir ve kalanlı bölme işlemi yaparız.",
      "Kesirler": "Kesirler, bir bütünün eş parçalara ayrıldığını gösterir. Bir pizzayı 4 eş parçaya ayırıp bir dilimini aldığında, sen pizzanın 1/4'ünü, yani çeyreğini almış olursun. Pay, payda ve kesir çizgisi gibi kavramları öğreniriz.",
      "Zaman Ölçme": "Zamanı ölçmek, planlı olmamıza yardım eder. Saat, dakika, saniye, gün, hafta, ay ve yıl arasındaki ilişkileri öğreniriz.",
      "Paralarımız": "Para, ihtiyaçlarımızı ve isteklerimizi almak için kullandığımız bir araçtır. Alışveriş yaparken lira ve kuruş hesaplamaları yapmayı, problem çözmeyi öğreniriz.",
      "Tartma": "Nesnelerin ağırlığını ölçmek için kilogram (kg) ve gram (g) kullanırız. 1 kilogramın 1000 grama eşit olduğunu ve bu birimlerle ölçüm yapmayı öğreniriz.",
      "Geometrik Cisimler ve Şekiller": "Küp, kare prizma, dikdörtgen prizma, üçgen prizma, silindir, koni ve küre gibi geometrik cisimleri ve onların yüz, köşe ve ayrıt sayılarını öğreniriz.",
      "Geometrik Örüntüler": "Şekillerin veya nesnelerin belirli bir kurala göre sıralanmasıyla oluşan örüntüleri devam ettirmeyi ve kendi örüntümüzü oluşturmayı öğreniriz.",
      "Geometride Temel Kavramlar": "Nokta, doğru, ışın ve açı gibi geometrinin temel kavramlarını tanırız. Açıları dar, dik, geniş ve doğru açı olarak sınıflandırırız.",
      "Uzamsal İlişkiler": "Simetri konusunu derinleştiririz. Bir şeklin simetri doğrusuna göre simetriğini çizmeyi öğreniriz.",
      "Uzunluk Ölçme": "Uzunlukları ölçmek için metre (m) ve santimetre (cm) arasındaki ilişkiyi öğreniriz. 1 metrenin 100 santimetreye eşit olduğunu ve bu birimlerle problem çözmeyi öğreniriz.",
      "Çevre Ölçme": "Bir şeklin etrafındaki tüm kenarların uzunlukları toplamına çevre denir. Kare ve dikdörtgenin çevre uzunluğunu hesaplamayı öğreniriz.",
      "Alan Ölçme": "Alan, bir yüzeyin kapladığı yerdir. Standart olmayan birimlerle (kare kağıt gibi) yüzeylerin alanını kaplayarak bulmayı öğreniriz.",
      "Sıvı Ölçme": "Sıvıları ölçmek için litre (L) ve mililitre (mL) arasındaki ilişkiyi öğreniriz. 1 litrenin 1000 mililitreye eşit olduğunu ve bu birimlerle problem çözmeyi öğreniriz."
    },
    "Hayat Bilgisi": {
      "Okulumuzda Hayat": "Okulun ve sınıfın kurallarına uymanın, arkadaşlarımıza karşı davranışlarımızın ve grup çalışmalarında iş birliğinin önemini öğreniriz.",
      "Evimizde Hayat": "Ailemizdeki görev ve sorumluluklarımızı, kaynakları bilinçli kullanmayı (elektrik, su) ve aile içi karar alma süreçlerine katılmayı öğreniriz.",
      "Sağlıklı Hayat": "Kişisel bakımımızı yapmanın, dengeli beslenmenin ve mevsimine uygun giyinmenin sağlığımız için önemini kavrarız.",
      "Güvenli Hayat": "Trafik kurallarına uymanın, tanımadığımız kişilere karşı dikkatli olmanın ve teknolojik aletleri güvenli kullanmanın yollarını öğreniriz.",
      "Ülkemizde Hayat": "Atatürk'ün hayatını, ülkemizin yönetim şekli olan cumhuriyeti ve milli bayramlarımızın anlam ve önemini öğreniriz.",
      "Doğada Hayat": "Bitki ve hayvanların yaşam döngülerini, geri dönüşümün önemini ve doğal afetlere karşı nasıl hazırlıklı olacağımızı öğreniriz."
    },
    "Yabancı Dil": {
      "Greeting": "Selamlaşma ve vedalaşma ifadelerini öğreniriz: 'Hello!', 'Good morning!', 'How are you?', 'Goodbye!' gibi.",
      "My Family": "Aile üyelerini tanıtırız: 'This is my mother.' (Bu benim annem), 'He is my father.' (O benim babam) gibi.",
      "People I Love": "Sevdiğimiz insanları ve arkadaşlarımızı tanıtırız. 'She is my best friend.' (O benim en iyi arkadaşım).",
      "Feelings": "Duygularımızı ifade edelim: 'I am happy' (Mutluyum). 'I am sad' (Üzgünüm). 'Are you happy?' (Mutlu musun?) 'Yes, I am' (Evet, mutluyum).",
      "Toys and Games": "Oyuncaklarımızın ve oyunların İngilizce isimlerini öğreniriz: 'doll' (oyuncak bebek), 'ball' (top), 'hide and seek' (saklambaç) gibi.",
      "My House": "Evimizin bölümlerini ve odaları öğreniriz: 'kitchen' (mutfak), 'bedroom' (yatak odası), 'living room' (oturma odası) gibi.",
      "In My City": "Şehirdeki yerleri öğreniriz: 'school' (okul), 'hospital' (hastane), 'park' (park), 'mosque' (cami) gibi.",
      "Transportation": "Ulaşım araçlarını öğreniriz: 'car' (araba), 'bus' (otobüs), 'plane' (uçak), 'train' (tren) gibi.",
      "Weather": "Hava durumunu soralım: 'What's the weather like today?' (Bugün hava nasıl?). Cevap verelim: 'It's sunny' (Hava güneşli). 'It's rainy' (Hava yağmurlu).",
      "Nature": "Doğayla ilgili temel kelimeleri öğreniriz: 'tree' (ağaç), 'flower' (çiçek), 'sun' (güneş), 'mountain' (dağ) gibi."
    },
    "Fen Bilimleri": {
      "GEZEGENİMİZİ TANIYALIM": "Yaşadığımız gezegen olan Dünya'nın şekli ve yapısı hakkında temel bilgileri öğreneceğiz.",
      "Dünya’nın Şekli": "Gezegenimiz Dünya'nın, tıpkı bir portakal gibi, küre şeklinde olduğunu ve bunun kanıtlarını öğreniriz.",
      "Dünya’nın Yapısı": "Gezegenimiz Dünya, katmanlardan oluşur. Tıpkı bir şeftali gibi! Şeftalinin çekirdeği Dünya'nın merkezi (Ağır Küre), etli kısmı magma (Ateş Küre) ve ince kabuğu da bizim yaşadığımız yer kabuğudur (Taş Küre).",
      "BEŞ DUYUMUZ": "Etrafımızdaki dünyayı nasıl algıladığımızı ve duyu organlarımızın görevlerini öğreneceğiz.",
      "Duyu Organları Ve Görevleri": "Etrafımızdaki dünyayı beş duyu organımızla anlarız: Gözlerimizle (görme), kulaklarımızla (işitme), burnumuzla (koklama), dilimizle (tatma) ve derimizle (dokunma) algılarız.",
      "KUVVETİ TANIYALIM": "Cisimleri hareket ettiren veya durduran kuvvetin ne olduğunu ve çeşitlerini öğreneceğiz.",
      "Varlıkların Hareket Özellikleri": "Varlıkların hızlanma, yavaşlama, dönme, sallanma ve yön değiştirme gibi farklı hareket özellikleri olduğunu öğreniriz.",
      "Cisimleri Hareket Ettirme Ve Durdurma": "Bir cismi hareket ettirmek için itme veya çekme kuvveti uygulamamız gerektiğini, hareket eden bir cismi ise zıt yönde bir kuvvetle yavaşlatıp durdurabileceğimizi öğreniriz.",
      "MADDEYİ TANIYALIM": "Çevremizdeki her şeyin bir madde olduğunu ve maddelerin özelliklerini ve hallerini öğreneceğiz.",
      "Maddeyi Niteleyen Özellikler": "Maddeleri sertlik-yumuşaklık, esneklik-kırılganlık, pürüzlü-pürüzsüz gibi duyu organlarımızla algıladığımız özelliklerine göre sınıflandırırız.",
      "Maddenin Hâlleri": "Maddenin üç hali vardır: katı, sıvı ve gaz. Buz katıdır, eriyince su olur (sıvı), kaynayınca da buhar olur (gaz). Maddeler ısı alarak veya vererek hal değiştirebilir.",
      "ÇEVREMİZDEKİ IŞIK VE SESLER": "Görmemizi ve duymamızı sağlayan ışık ve sesin kaynaklarını ve özelliklerini öğreneceğiz.",
      "Işığın Görmedeki Rolü": "Bir cismi görebilmemiz için o cisimden gözümüze ışık gelmesi gerektiğini öğreniriz. Işık olmadan göremeyiz.",
      "Işık Kaynakları": "Işığın doğal (Güneş, yıldızlar) ve yapay (ampul, mum) kaynakları olduğunu öğreniriz. Ay'ın bir ışık kaynağı olmadığını, Güneş'ten aldığı ışığı yansıttığını anlarız.",
      "Çevremizdeki Sesler": "Her sesin bir kaynağı olduğunu ve seslerin doğal (kuş sesi) ve yapay (araba kornası) kaynakları olduğunu öğreniriz.",
      "Sesin İşitmede ki Rolü": "Sesin şiddetinin işitmedeki önemini ve ses kirliliğinin olumsuz etkilerini öğreniriz.",
      "CANLILAR DÜNYASINA YOLCULUK": "Çevremizdeki canlı ve cansız varlıkları ayırt etmeyi ve bitkilerle hayvanların yaşam döngülerini öğreneceğiz.",
      "Çevremizdeki Varlıkları Tanıyalım": "Doğadaki varlıkları canlı (insan, hayvan, bitki) ve cansız (taş, su, hava) olarak sınıflandırırız. Canlıların ortak özelliklerini (büyüme, beslenme, hareket etme vb.) öğreniriz.",
      "ELEKTRİKLİ ARAÇLAR": "Günlük hayatta kullandığımız elektrikli araçları ve elektriği nasıl güvenli kullanacağımızı öğreneceğiz.",
      "Elektrikli Araç Gereçler": "Evde kullandığımız buzdolabı, televizyon, lamba gibi araçların elektrikle çalıştığını ve hayatımızı kolaylaştırdığını öğreniriz.",
      "Elektrik Kaynakları": "Elektrikli aletlerin çalışması için şehir elektriği, pil veya batarya gibi farklı elektrik kaynaklarına ihtiyaç duyduğunu öğreniriz.",
      "Elektriğin Güvenli Kullanımı": "Elektriğin tehlikeli olabileceğini ve ıslak elle prizlere dokunmamak, kablolarla oynamamak gibi güvenlik kurallarına uymamız gerektiğini öğreniriz."
    }
  },
  4: {
    "Türkçe": {
      "OKUMA": "Dördüncü sınıfta artık birer okuma ustası oluyoruz! Metinlerin sadece ne anlattığını değil, yazarın bize ne demek istediğini, yani ana fikrini de bulacağız. Gerçek ve hayal ürünlerini ayırt edip, cümleler arasındaki gizli bağlantıları (neden-sonuç gibi) keşfedeceğiz.",
      "Metnin Konusu": "Bir metnin en çok ne hakkında konuştuğunu bulmaktır. 'Bu metnin konusu nedir?' sorusu, bize metnin genel çerçevesini verir.",
      "Ana Fikir/Ana Duygu": "Ana fikir, yazarın okuyucuya vermek istediği asıl mesaj veya derstir. Ana duygu ise bir şiirin bizde uyandırdığı temel histir (sevinç, hüzün, özlem gibi).",
      "5N 1K": "Bir metni tam olarak anlamak için dedektif gibi 5N 1K sorularını sorarız: Kim, Ne, Nerede, Ne zaman, Nasıl ve Neden? Bu soruların cevapları, metnin tüm sırlarını ve iskeletini ortaya çıkarır.",
      "Başlık Belirleme": "Başlık, metnin içeriğini en iyi özetleyen isimdir. Metnin konusunu veya ana fikrini bulduktan sonra ona en uygun başlığı verebiliriz.",
      "Görsel Okuma": "Bir resim, fotoğraf, afiş veya tablodaki bilgileri ve mesajları doğru bir şekilde yorumlama becerisidir.",
      "Metinle İlgili Sorular Sorma ve Soruları Cevaplama": "Okuduğumuz bir metin hakkında merak ettiklerimizi soruya dönüştürmek ve metnin içinde bu soruların cevaplarını aramak, okuduğumuzu daha derinlemesine anlamamızı sağlar.",
      "Hikâye Unsurları": "Bir hikayeyi oluşturan temel ögelerdir: Ana karakter ve yardımcı karakterler (şahıs kadrosu), olayın geçtiği yer, zaman ve anlatılan olayın kendisi.",
      "Metin Türleri": "Yazıların amaçlarına göre farklı türleri vardır. Hikaye edici, bilgilendirici ve şiir gibi metin türlerinin özelliklerini ayırt etmeyi öğreniriz.",
      "Metnin Bölümleri": "Her yazının genellikle bir girişi, gelişmesi ve sonucu olur. Girişte konu tanıtılır, gelişmede olaylar anlatılır, sonuçta ise bir mesaja bağlanır.",
      "Gerçek ve Hayal Unsurları": "Gerçek unsurlar, dünyamızda olabilecek şeylerdir, örneğin 'Kuşlar ilkbaharda yuva yapar'. Hayal unsurları ise sadece hayal gücümüzde olan şeylerdir, örneğin 'Bulutlar pamuk şekerden yapılmıştı'.",
      "Karşılaştırma Yapma": "İki veya daha fazla varlık ya da kavram arasındaki benzerlikleri ve farklılıkları belirten cümlelerdir. 'Ali, Ayşe'den daha uzundur' bir karşılaştırma cümlesidir.",
      "Neden-Sonuç Cümleleri": "Bir eylemin hangi nedenle yapıldığını bildiren cümlelerdir. 'Yağmur yağdığı için şemsiyemi aldım' cümlesinde, şemsiyeyi almamın nedeni yağmurun yağmasıdır.",
      "Benzetme Cümleleri": "Anlatımı güçlendirmek için iki farklı şey arasında ortak bir özellikten yola çıkarak benzerlik kurmaktır. 'Kar gibi beyaz dişleri vardı' cümlesinde dişler, beyazlık yönünden kara benzetilmiştir.",
      "Örneklendirme Cümleleri": "Soyut bir düşünceyi daha anlaşılır hale getirmek için somut örnekler vermektir. 'Sağlıklı beslenmeliyiz. Örneğin, bol bol meyve ve sebze yemeliyiz.'",
      "YAZMA": "Dördüncü sınıfta artık düşüncelerimizi daha planlı ve kurallara uygun bir şekilde yazıya dökme zamanı! Yazılarımızın trafik işaretleri olan noktalama ve yazım kurallarında ustalaşacağız.",
      "Olayların Oluş Sırası": "Bir olayı anlatırken, yaşananları kronolojik sıraya göre (önce, sonra, en sonunda) yazmak, anlatımın anlaşılır olmasını sağlar.",
      "Büyük Harflerin Kullanımı": "Cümle başları, özel isimler, gezegen adları, kitap ve dergi adları, kurum adları gibi birçok yerde büyük harflerin doğru kullanımını pekiştiririz.",
      "Kısaltmaların Yazımı": "Kurum adlarının (TÜBİTAK gibi) veya bazı kelimelerin (Prof. gibi) kısaltmalarının nasıl yazıldığını ve bu kısaltmalara gelen eklerin nasıl ayrıldığını öğreniriz.",
      "Sayıların Yazımı ve Romen Rakamları": "Sayıların yazıyla mı rakamla mı yazılması gerektiğini, ayrıca I, V, X gibi Romen rakamlarını okumayı ve yazmayı öğreniriz.",
      "'De' ve 'Ki' Bağlaçlarının Yazımı": "Bu eklerin ayrı mı bitişik mi yazılacağını anlamanın kolay bir yolu var. Cümleden çıkardığımızda anlam bozulmuyorsa, o bir bağlaçtır ve ayrı yazılır. 'Ben de geldim' -> 'Ben geldim' (anlamlı, demek ki ayrı).",
      "Pekiştirmeli Sözcüklerin Yazımı": "Anlamı güçlendirmek için kullanılan 'tertemiz', 'masmavi', 'sımsıcak' gibi pekiştirmeli sözcüklerin her zaman bitişik yazıldığını öğreniriz.",
      "Noktalama İşaretleri": "Nokta, virgül, soru işareti, ünlem, kesme işareti, tırnak işareti, iki nokta, parantez gibi birçok noktalama işaretinin görevlerini ve doğru kullanım yerlerini öğreniriz.",
      "SÖZ VARLIĞI": "Kelime hazinemizi daha da zenginleştiriyoruz! Kelimelerin sadece ilk anlamlarını değil, mecaz ve terim anlamlarını, deyimleri ve atasözlerini de öğrenerek dilimizin ne kadar derin olduğunu keşfedeceğiz.",
      "Eş Anlamlı Sözcükler": "Yazılışları farklı, anlamları aynı olan kelimelerdir. Örneğin 'okul' ve 'mektep', 'cevap' ve 'yanıt' gibi.",
      "Zıt Anlamlı Sözcükler": "Anlamca birbirinin tam karşıtı olan kelimelerdir. Örneğin 'siyah' ve 'beyaz', 'ileri' ve 'geri' gibi.",
      "Eş Sesli Sözcükler": "Yazılışları aynı, anlamları tamamen farklı olan kelimelerdir. 'Yüz' kelimesi hem sayı, hem suratımız, hem de yüzme eylemi anlamına gelebilir.",
      "Gerçek Mecaz ve Terim Anlam": "Gerçek anlam kelimenin akla gelen ilk anlamıdır ('kolum kırıldı'). Mecaz anlam, gerçek anlamdan tamamen uzaklaşmış yeni anlamdır ('sınavdan kötü not alınca kolum kanadım kırıldı'). Terim anlam ise bir bilim, sanat veya meslek dalına özgü anlamdır ('üçgenin iç açıları').",
      "Sözcüklerin ve Sözcük Gruplarının Anlamı": "Cümledeki bir kelimenin veya kelime grubunun ne anlama geldiğini, cümlenin genel bağlamından yola çıkarak tahmin etme becerisidir.",
      "Yabancı Sözcüklerin Yerine Türkçelerini Kullanma": "Dilimize yabancı dillerden girmiş bazı kelimeler yerine, onların Türkçe karşılıklarını kullanmanın dilimizi korumak için önemli olduğunu öğreniriz. Örneğin, 'selfie' yerine 'özçekim' kullanmak gibi.",
      "Deyimler ve Atasözleri": "'Etekleri zil çalmak' dediğimizde, gerçekten eteğinde zil olduğunu değil, birinin çok sevindiğini anlarız. Deyimler ve atasözleri, kısa ve özlü bir şekilde derin anlamlar ifade eden kalıplaşmış sözlerdir."
    },
    "Matematik": {
      "DOĞAL SAYILAR": "Artık daha büyük sayılarla tanışma zamanı! 4, 5 ve 6 basamaklı sayıları okuyacak, yazacak, çözümleyecek ve onlarla ilgili işlemler yapacağız.",
      "Doğal Sayılar": "4, 5 ve 6 basamaklı sayıları okumayı ve yazmayı öğreniriz.",
      "Yüzer ve Biner Sayma": "100'den başlayarak yüzer yüzer veya 1000'den başlayarak biner biner ileriye doğru ritmik sayma yaparız.",
      "Bölük, Basamak ve Çözümleme": "Çok büyük sayıları okumak için onları bölüklere ayırırız. 'Birler Bölüğü' ve 'Binler Bölüğü' gibi. Bir sayıyı basamak değerlerinin toplamı şeklinde yazmaya ise çözümleme denir.",
      "Doğal Sayıları Yuvarlama": "Sayıları en yakın onluğa veya yüzlüğe yuvarlayarak hesaplamaları kolaylaştırmayı öğreniriz.",
      "Doğal Sayıları Sıralama": "Verilen sayıları küçükten büyüğe veya büyükten küçüğe doğru sıralamak için aralarına '<' veya '>' işaretlerini koyarız.",
      "Sayı Örüntüleri": "Sayı örüntüleri, gizli bir kuralı olan sihirli sayı dizileridir. Görevimiz, bu gizli kuralı keşfederek örüntüyü devam ettirmektir! 27, 31, 35,... dizisinin kuralı '+4'tür.",
      "DOĞAL SAYILARLA TOPLAMA İŞLEMİ": "Büyük sayılarla toplama işlemi yapmayı, sonucu tahmin etmeyi ve zihinden toplama stratejilerini öğreneceğiz.",
      "Toplama İşlemi": "4, 5 ve 6 basamaklı sayılarla eldeli toplama işlemi yapmayı öğreniriz.",
      "DOĞAL SAYILARLA ÇIKARMA İŞLEMİ": "Büyük sayılarla çıkarma işlemi yapmayı ve zihinden çıkarma yöntemlerini öğreneceğiz.",
      "Çıkarma İşlemi": "Büyük sayılarla onluk ve yüzlük bozarak çıkarma işlemi yapmayı öğreniriz.",
      "Zihinden Çıkarma İşlemi": "100'ün ve 1000'in katlarıyla zihinden çıkarma işlemi yapma stratejilerini öğreniriz. Örneğin 5000 - 2000 = 3000 gibi.",
      "Toplama İşleminde Tahmin": "Toplama işlemi yapmadan önce, sayıları en yakın onluğa veya yüzlüğe yuvarlayarak işlemin sonucunu yaklaşık olarak tahmin ederiz.",
      "Zihinden Toplama": "Sayıları parçalara ayırma veya üzerine sayma gibi farklı stratejiler kullanarak büyük sayılarla zihinden toplama yaparız.",
      "Toplama İşlemiyle Problem Çözelim": "Günlük hayatta karşılaştığımız ve toplama işlemi gerektiren problemleri çözmeyi öğreniriz.",
      "Çıkarma İşleminde Tahmin": "Sayıları en yakın onluğa veya yüzlüğe yuvarlayarak çıkarma işleminin sonucunu yaklaşık olarak tahmin ederiz.",
      "Çıkarma İşlemiyle Problem Çözelim": "Günlük hayatta karşılaştığımız ve çıkarma işlemi gerektiren problemleri çözmeyi öğreniriz.",
      "DOĞAL SAYILARLA ÇARPMA İŞLEMİ": "Çarpma işleminde ustalaşıyoruz! Büyük sayılarla çarpma ve problem çözme becerilerimizi geliştireceğiz.",
      "Çarpma İşlemi": "En çok üç basamaklı sayılarla en çok iki basamaklı sayıları çarpmayı öğreniriz.",
      "Çarpma İşleminde Çarpanların Sırası": "Çarpma işleminde çarpanların yerini değiştirdiğimizde sonucun değişmediğini öğreniriz. 5 x 3 ile 3 x 5 aynıdır!",
      "Zihinden Çarpma": "Bir sayıyı 10, 100 ve 1000 ile zihinden, yani kısa yoldan çarpmayı öğreniriz. Bir sayıyı 10 ile çarpmak için sonuna bir sıfır eklemek yeterlidir.",
      "Çarpma İşleminde Tahmin": "Çarpanları en yakın onluğa yuvarlayarak çarpma işleminin sonucunu yaklaşık olarak tahmin ederiz.",
      "Çarpma İşlemiyle Problem Çözelim": "Günlük hayatta karşılaştığımız ve çarpma işlemi gerektiren problemleri (kat problemleri gibi) çözmeyi öğreniriz.",
      "DOĞAL SAYILARLA BÖLME İŞLEMİ": "Bölme işleminde daha ileri adımlar atacak ve çarpma ile bölme arasındaki ilişkiyi keşfedeceğiz.",
      "Bölme İşlemi": "En çok üç basamaklı sayıları en çok iki basamaklı sayılara bölmeyi öğreniriz.",
      "Kısa Yoldan Bölme": "Bir sayıyı 10, 100 ve 1000'e zihinden, yani kısa yoldan bölmeyi öğreniriz. Sonu sıfırlı bir sayıyı 10'a bölmek için sonundan bir sıfır silmek yeterlidir.",
      "Bölme İşleminde Tahmin": "Bölünen ve böleni en yakın onluğa veya yüzlüğe yuvarlayarak bölme işleminin sonucunu yaklaşık olarak tahmin ederiz.",
      "Çarpma ile Bölme Arasındaki İlşki": "Çarpma ve bölme işlemlerinin birbirinin tersi olduğunu öğreniriz. Bölme işleminin doğruluğunu çarpma yaparak kontrol edebiliriz.",
      "Bölme İşlemiyle Problem Çözelim": "Eşit paylaştırma veya gruplama gerektiren günlük hayat problemlerini bölme işlemiyle çözeriz.",
      "Matematiksel İfadeler": "Parantezli işlemlerde işlem önceliğini öğreniriz. Önce parantez içindeki işlemin yapılması gerektiğini kavrarız.",
      "KESİRLER": "Kesir çeşitlerini tanıyacak ve kesirleri karşılaştırmayı öğreneceğiz.",
      "Basit, Bileşik ve Tam Sayılı Kesir": "Payı paydasından küçük olan kesirlere basit kesir (1/4 gibi), payı paydasına eşit veya büyük olan kesirlere bileşik kesir (5/4 gibi), bir tam sayı ve bir basit kesirden oluşan kesirlere ise tam sayılı kesir denir.",
      "Birim Kesir": "Payı 1 olan kesirlere birim kesir denir (1/2, 1/5, 1/10 gibi). Birim kesirleri karşılaştırmayı ve sıralamayı öğreniriz.",
      "Bir Çokluğun Kesir Kadarını Bulma": "Verilen bir bütünün istenen kesir kadarını bulmaktır. '20 elmanın 1/4'ü kaç elmadır?' gibi problemleri çözmek için bütünü paydaya böler, pay ile çarparız.",
      "Kesirleri Karşılaştırma": "Paydaları eşit olan veya payları eşit olan kesirleri karşılaştırarak hangisinin daha büyük veya küçük olduğunu buluruz.",
      "KESİRLERLE İŞLEMLER": "Kesirlerle en temel işlemler olan toplama ve çıkarmayı öğreneceğiz.",
      "Kesirlerle Toplama ve Çıkarma İşlemi": "Paydaları eşit olan kesirlerle toplama ve çıkarma işlemi yapmayı öğreniriz. Paylar toplanır veya çıkarılır, ortak payda ise aynen yazılır.",
      "Kesir İşlemleriyle Problem Çözelim": "Kesirlerle toplama ve çıkarma işlemi gerektiren problemleri çözmeyi öğreniriz.",
      "ZAMAN ÖLÇME": "Zamanı ölçme birimleri arasındaki ilişkileri daha derinlemesine inceleyeceğiz.",
      "Zamanı Ölçme Birimleri": "Yıl, ay, hafta, gün, saat, dakika ve saniye arasındaki ilişkileri öğreniriz. Örneğin, 1 yılın 12 ay, 1 haftanın 7 gün olduğunu kavrarız.",
      "Zamanı Ölçme İle İlgili Problem Çözelim": "Zaman birimlerini kullanarak dönüşüm gerektiren problemleri çözeriz. 'Saat 14:30'da başlayan bir etkinlik 90 dakika sürerse, saat kaçta biter?' gibi.",
      "VERİ TOPLAMA VE DEĞERLENDİRME": "Topladığımız verileri artık daha gelişmiş bir grafik olan sütun grafiği ile göstermeyi öğreneceğiz.",
      "Sütun Grafiği": "Araştırma sonuçlarını sütunlar kullanarak gösteren bir grafiktir. Sütunların uzunluğu, verinin miktarını gösterir. Sütun grafiklerini okumayı, yorumlamayı ve oluşturmayı öğreniriz.",
      "Verilerin Farklı Gösterimi": "Aynı verinin hem tablo hem de sütun grafiği gibi farklı şekillerde gösterilebileceğini ve bu gösterimler arasında geçiş yapmayı öğreniriz.",
      "Veri Problemleri": "Tablo ve sütun grafiklerini yorumlayarak verilerle ilgili problemleri çözeriz.",
      "GEOMETRİK CİSİMLER VE ŞEKİLLER": "Üçgen, kare ve dikdörtgen gibi temel şekilleri ve küp gibi cisimleri daha detaylı inceleyeceğiz.",
      "Üçgen, Kare ve Dikdörtgen": "Bu şekillerin temel özelliklerini, kenar ve köşe sayılarını, ayrıca kenarlarının ve açılarının isimlendirilmesini öğreniriz.",
      "Üçgenlerin Kenar Uzunlukları": "Üçgenleri kenar uzunluklarına göre eşkenar (tüm kenarları eşit), ikizkenar (iki kenarı eşit) ve çeşitkenar (tüm kenarları farklı) olarak sınıflandırırız.",
      "Küp": "Küpün 6 yüzü, 12 ayrıtı ve 8 köşesi olduğunu, tüm yüzlerinin karesel bölgelerden oluştuğunu ve küpün açınımını çizmeyi öğreniriz.",
      "GEOMETRİDE TEMEL KAVRAMLAR": "Geometrinin en temel yapı taşları olan düzlem ve açıları tanıyacağız.",
      "Düzlem": "Düzlemin, bir masanın yüzeyi veya bir duvar gibi pürüzsüz ve sonsuza kadar uzanan bir yüzey olduğunu ve bazı şekillerin düzlemsel olduğunu öğreniriz.",
      "Açılar": "Açıları, açıölçer (iletki) kullanarak ölçmeyi ve açıları ölçülerine göre dar, dik, geniş ve doğru açı olarak sınıflandırmayı öğreniriz.",
      "UZAMSAL İLİŞKİLER": "Simetri konusunu daha derinlemesine işleyeceğiz.",
      "Simetri": "Bir şeklin, bir doğruya göre simetriğini çizmeyi ve simetrik şekiller oluşturmayı öğreniriz.",
      "UZUNLUK ÖLÇME": "Metre, santimetre ve yeni birimimiz kilometre arasındaki ilişkileri öğreneceğiz.",
      "Uzunluk Ölçme": "Metre (m), santimetre (cm) ve kilometre (km) arasındaki ilişkileri öğreniriz. 1 km'nin 1000 metreye eşit olduğunu kavrarız.",
      "Uzunlukları Ölçme İle İlgili Problem Çözelim": "Uzunluk ölçü birimleri arasında dönüşüm gerektiren problemleri çözeriz.",
      "ÇEVRE ÖLÇME": "Şekillerin çevre uzunluklarını hesaplamada ustalaşacağız.",
      "Çevre Uzunlukları": "Kare ve dikdörtgenin çevre uzunluklarını, kenar uzunluklarını kullanarak formüllerle hesaplamayı öğreniriz.",
      "Şekillerin Çevre Uzunluk Problemleri": "Çevre uzunluğu verilen bir karenin bir kenar uzunluğunu bulmak gibi problemleri çözeriz.",
      "ALAN ÖLÇME": "Alan kavramını ve nasıl hesaplandığını öğreneceğiz.",
      "Şekillerin Alanı": "Bir şeklin alanının, o şeklin yüzeyini kaplayan birim karelerin sayısı olduğunu öğreniriz.",
      "Kare ve Dikdörtgenin Alanı": "Kare ve dikdörtgenin alanını, kenar uzunluklarını çarparak bulan formülü öğrenir ve uygularız.",
      "TARTMA": "Ağırlık ölçü birimlerine ton ve miligramı da ekleyeceğiz.",
      "Kilogram ve Gram": "Kilogram (kg) ve gram (g) arasındaki ilişkiyi (1 kg = 1000 g) pekiştirir ve bu birimlerle problem çözeriz.",
      "Ton ve Miligram": "Çok büyük ağırlıklar için ton (t), çok küçük ağırlıklar için ise miligram (mg) kullanıldığını öğreniriz.",
      "Tartma Birimleri Arasındaki İlişkiler": "Ton, kilogram, gram ve miligram arasında dönüşümler yapar ve bu birimlerle ilgili problemleri çözeriz.",
      "SIVI ÖLÇME": "Sıvı ölçme birimlerini ve aralarındaki ilişkileri öğreneceğiz.",
      "Litre ve Mililitre": "Litre (L) ve mililitre (mL) arasındaki ilişkiyi (1 L = 1000 mL) pekiştirir ve bu birimlerle ilgili problemleri çözeriz.",
      "Litre ve Mililitre Problemleri": "Sıvı ölçü birimleri arasında dönüşüm gerektiren problemleri çözeriz."
    },
    "Fen Bilimleri": {
      "YER KABUĞU VE DÜNYA'MIZIN HAREKETLERİ": "Yaşadığımız yer olan yer kabuğunun yapısını ve gezegenimizin uzaydaki hareketlerini öğreneceğiz.",
      "Yer Kabuğunun Yapısı": "Yer kabuğunun kayaçlardan oluştuğunu, kayaçların içinde maden ve fosil gibi değerli yapılar bulunduğunu öğreniriz.",
      "Dünya'mızın Hareketleri": "Dünya'nın kendi ekseni etrafında dönme hareketi yaptığını (gece ve gündüz oluşur) ve Güneş'in etrafında dolanma hareketi yaptığını (mevsimler oluşur) öğreniriz.",
      "BESİNLERİMİZ": "Yaşamak için ihtiyacımız olan besinlerin çeşitlerini ve sağlıklı bir yaşam için nasıl beslenmemiz gerektiğini öğreneceğiz.",
      "Besinler ve Özellikleri": "Besinleri protein, karbonhidrat, yağ, vitamin, su ve mineral olarak gruplandırır ve hangi yiyeceklerde hangi besinlerin bulunduğunu öğreniriz.",
      "Sağlıklı Yaşam": "Dengeli beslenmenin, spor yapmanın ve kişisel hijyenin sağlıklı bir yaşam için ne kadar önemli olduğunu, ayrıca sigara ve alkol gibi zararlı alışkanlıklardan uzak durmamız gerektiğini öğreniriz.",
      "KUVVETİN ETKİLERİ": "Kuvvetin cisimler üzerindeki etkilerini ve mıknatısların gizemli kuvvetini keşfedeceğiz.",
      "Kuvvetin Cisimler Üzerindeki Etkileri": "Kuvvetin, cisimleri hareket ettirebileceğini, durdurabileceğini, yönünü veya şeklini değiştirebileceğini örneklerle öğreniriz.",
      "Mıknatısların Uyguladığı Kuvvet": "Mıknatısların görünmez bir gücü vardır! Zıt kutupları (N-S) birbirini çekerken, aynı kutupları (N-N, S-S) birbirini iter. Mıknatıslar sadece demir, nikel ve kobalt gibi maddeleri çekerler.",
      "MADDENİN ÖZELLİKLERİ": "Maddenin hallerini, ısı etkisiyle nasıl değiştiklerini ve karışımları daha detaylı inceleyeceğiz.",
      "Maddeyi Niteleyen Özellikler": "Maddeleri suda yüzme-batma, suyu emme-emmeme ve mıknatısla çekilme gibi özelliklerine göre sınıflandırırız.",
      "Maddenin Ölçülebilir Özellikleri": "Maddenin kütlesini (eşit kollu terazi ile) ve hacmini (dereceli silindir ile) ölçmeyi öğreniriz.",
      "Maddenin Hâlleri": "Maddenin doğada katı, sıvı ve gaz olmak üzere üç halde bulunduğunu ve bu hallerin temel özelliklerini (şekil, akışkanlık vb.) öğreniriz.",
      "Maddenin Isı Etkisiyle Değişimi": "Maddelerin ısı alarak (erime, buharlaşma) veya ısı vererek (donma, yoğuşma) hal değiştirdiğini öğreniriz.",
      "Saf Madde ve Karışım": "Saf madde tek bir şeyden oluşur (su veya tuz gibi). Karışım ise birden fazla maddenin bir araya gelmesidir (salata veya şekerli su gibi). Karışımları ayırmak için süzme, eleme ve mıknatısla ayırma gibi yöntemler kullanırız.",
      "AYDINLATMA VE SES TEKNOLOJİLERİ": "Geçmişten günümüze ışık ve ses teknolojilerinin nasıl geliştiğini ve hayatımızı nasıl değiştirdiğini öğreneceğiz.",
      "Aydınlatma Teknolojileri": "Geçmişte kullanılan meşale, gaz lambası gibi aydınlatma araçlarından günümüzdeki ampul, floresan ve LED lambalara kadar olan teknolojik gelişimi inceleriz.",
      "Geçmişten Günümüze Ses Teknolojileri": "Sesin şiddetini değiştiren teknolojileri (mikrofon, hoparlör) ve sesi kaydeden teknolojilerin (gramofon, kaset, CD) gelişimini öğreniriz. Ses kirliliğinin nedenlerini ve çözümlerini tartışırız.",
      "İNSAN VE ÇEVRE": "Bilinçli bir tüketici olmanın çevre için ne kadar önemli olduğunu öğreneceğiz.",
      "Bilinçli Tüketici": "Alışveriş yaparken ürünlerin üretim ve son kullanma tarihlerine bakmanın, TSE damgasını kontrol etmenin ve israftan kaçınmanın bilinçli bir tüketici olmanın gereklilikleri olduğunu öğreniriz.",
      "BASİT ELEKTRİK DEVRELERİ": "Kendi elektrik devremizi kurmayı ve devre elemanlarının görevlerini öğreneceğiz.",
      "Basit Elektrik Devreleri": "Basit bir elektrik devresi; pil (güç kaynağı), ampul (ışık kaynağı), bağlantı kablosu (yol) ve anahtardan (kontrol) oluşur. Elektriğin akması ve ampulün yanması için devrenin kapalı, yani kesintisiz bir yol olması gerekir."
    },
    "Sosyal Bilgiler": {
      "BİREY VE TOPLUM": "Her bireyin eşsiz olduğunu, bir kimliği ve bir geçmişi olduğunu öğreneceğiz.",
      "Resmî Kimlik Belgemiz": "T.C. Kimlik Kartımızın, bizim kim olduğumuzu gösteren resmi bir belge olduğunu ve üzerindeki bilgilerin (ad, soyad, doğum tarihi) ne anlama geldiğini öğreniriz.",
      "Yaşadıklarımızın Kronolojik Sıralaması": "Hayatımızdaki önemli olayları (doğum, okula başlama vb.) tarih sırasına göre dizerek kendi kişisel tarihimizi, yani kronolojimizi oluştururuz.",
      "Bireysel İlgi, İhtiyaç ve Yetenekler": "Her insanın farklı ilgileri (futbol oynamak), ihtiyaçları (beslenme) ve yetenekleri (güzel resim yapmak) olduğunu ve bu farklılıklara saygı duymamız gerektiğini öğreniriz.",
      "Farklılıklarımız": "İnsanların fiziksel özellikleri, duygusal tepkileri ve ilgi alanları bakımından birbirinden farklı olmasının doğal ve toplumu zenginleştiren bir durum olduğunu kavrarız.",
      "KÜLTÜR VE MİRAS": "Ailemizin ve milletimizin geçmişini, kültürel zenginliklerimizi ve Milli Mücadele'nin önemini öğreneceğiz.",
      "Aile Tarihimiz": "Aile büyüklerimizle (dede, nine) konuşarak, eski fotoğraf ve eşyalara bakarak ailemizin geçmişi hakkında bilgi ediniriz. Buna sözlü tarih denir.",
      "Millî Kültürümüz": "Bizi bir millet yapan ortak değerlerdir. Yemeklerimiz (baklava), halk oyunlarımız (zeybek), bayramlarımız ve geleneklerimiz milli kültürümüzün bir parçasıdır.",
      "Geleneksel Çocuk Oyunları": "Geçmişte oynanan ama günümüzde unutulmaya yüz tutmuş mendil kapmaca, seksek, körebe gibi geleneksel çocuk oyunlarını tanırız.",
      "Millî Mücadele": "Atatürk ve Türk milletinin, ülkemizi düşman işgalinden kurtarmak için verdiği kahramanca mücadelenin öyküsünü öğreniriz.",
      "İNSANLAR, YERLER VE ÇEVRELER": "Yaşadığımız çevreyi, harita ve krokileri, doğal ve beşerî unsurları ve doğal afetlere karşı nasıl korunacağımızı öğreneceğiz.",
      "Herhangi Bir Yerin Konumu": "Bir yerin konumunu tarif ederken çevresindeki bilinen yerlerden (okulun yanı, parkın karşısı) veya yönlerden (doğu, batı, kuzey, güney) faydalanırız.",
      "Krokinin Hayatımızdaki Yeri": "Kroki, bir yerin kuşbakışı, yani tepeden görünüşünün ölçüsüz, basit bir çizimidir. Bir arkadaşımıza evimizi tarif etmek veya odamızın planını çizmek için kroki kullanırız.",
      "Doğal ve Beşerî Unsurlar": "Doğada kendiliğinden var olan unsurlara (dağ, deniz, orman) doğal unsur; insanlar tarafından yapılmış unsurlara (bina, köprü, yol) ise beşerî unsur denir.",
      "Hava Olayları": "Havanın belirli bir yerdeki anlık durumudur. Güneşli, yağmurlu, karlı, rüzgarlı gibi hava olaylarını gözlemler ve hayatımızı nasıl etkilediğini öğreniriz.",
      "Yaşadığımız Yerin Coğrafi Özellikleri": "Yaşadığımız yerin (köy, şehir) dağ, ova, akarsu gibi yüzey şekillerini ve iklim özelliklerini tanırız.",
      "Doğal Afetler ve Korunma Yolları": "Doğal afetler deprem, sel gibi olaylardır. Bu afetler sırasında ve sonrasında neler yapmamız gerektiğini, bir 'Afet ve Acil Durum Çantası' hazırlamanın önemini öğreniriz.",
      "BİLİM, TEKNOLOJİ VE TOPLUM": "Teknolojinin hayatımızı nasıl değiştirdiğini, geçmişten günümüze nasıl geliştiğini ve onu nasıl doğru kullanmamız gerektiğini öğreneceğiz.",
      "Hayatımızda Teknoloji": "Teknolojinin eğitim (akıllı tahta), sağlık (röntgen cihazı), ulaşım (uçak) gibi birçok alanda hayatımızı nasıl kolaylaştırdığını fark ederiz.",
      "Teknolojik Ürünlerin Mucitleri": "Telefonu icat eden Graham Bell veya ampulü icat eden Edison gibi, hayatımızı kolaylaştıran teknolojik ürünleri geliştiren mucitleri tanırız.",
      "Teknolojik Ürünlerin Zaman İçinde Gelişimi": "Geçmişte kullanılan kömürlü ütüden günümüzdeki buharlı ütüye veya mektuptan e-postaya kadar teknolojinin zaman içinde nasıl geliştiğini inceleriz.",
      "Teknolojik Ürünleri Kullanalım": "Teknolojik ürünleri kullanırken hem kendi güvenliğimize (bilgisayar başında doğru oturmak) hem de ürünün kullanım kılavuzuna dikkat etmemiz gerektiğini öğreniriz.",
      "ÜRETİM, DAĞITIM VE TÜKETİM": "İhtiyaçlarımızı karşılayan ürünlerin bize nasıl ulaştığını ve bilinçli bir tüketici olmanın önemini öğreneceğiz.",
      "İstek ve İhtiyaçlarımız": "İhtiyaçlar (barınma, beslenme) hayati önem taşırken, istekler (yeni oyuncak) olmasa da yaşayabileceğimiz şeylerdir. Alışverişte ihtiyaçlarımıza öncelik vermeyi öğreniriz.",
      "Ekonomik Faaliyetler": "İnsanların geçimlerini sağlamak için yaptıkları işlerdir. Tarım, hayvancılık, sanayi, turizm gibi ekonomik faaliyetleri ve yaşadığımız çevrede hangilerinin yaygın olduğunu öğreniriz.",
      "Bilinçli Tüketici": "Alışveriş yaparken bütçemize dikkat eden, ürünlerin kalitesini ve son kullanma tarihini kontrol eden, israftan kaçınan kişidir.",
      "Kaynakları Bilinçli Kullanalım": "Su, elektrik, besin gibi kaynaklarımızın sınırsız olmadığını ve onları tasarruflu kullanmanın hem aile bütçemiz hem de dünyamız için önemli olduğunu öğreniriz.",
      "ETKİN VATANDAŞLIK": "Bir vatandaş olarak haklarımızı, sorumluluklarımızı ve özgürlüklerimizi öğreneceğiz.",
      "Çocuk Olarak Haklarımız": "Her çocuğun eğitim görme, sağlık hizmeti alma, oyun oynama, düşüncelerini özgürce ifade etme gibi temel hakları olduğunu öğreniriz.",
      "Sorumluluk Alalım": "Hem kendimize (ödevlerimizi yapmak) hem de ailemize (odamızı toplamak) ve topluma (çevreyi temiz tutmak) karşı sorumluluklarımız olduğunu kavrarız.",
      "Sosyal Kulüpler": "Okullardaki eğitsel ve sosyal kulüplerin (spor kulübü, müzik kulübü gibi) ilgi ve yeteneklerimizi geliştirmemize nasıl yardımcı olduğunu öğreniriz.",
      "Bireysel Özgürlük": "Her bireyin, başkalarına zarar vermeden, düşüncelerini ifade etme ve kendi kararlarını verme özgürlüğü olduğunu öğreniriz.",
      "KÜRESEL BAĞLANTILAR": "Sadece kendi ülkemizi değil, diğer dünya ülkelerini ve onlarla olan ilişkilerimizi de tanıyacağız.",
      "Ülkeleri Tanıyalım": "Farklı ülkelerin coğrafi konumları, bayrakları, başkentleri ve kültürel özellikleri hakkında genel bilgiler ediniriz.",
      "Türkiye'nin Komşuları ve Türk Cumhuriyetleri": "Ülkemizin komşu ülkelerini ve ortak tarihi ve kültürel bağlarımızın olduğu Türk Cumhuriyetlerini (Azerbaycan, Kazakistan gibi) harita üzerinde tanırız.",
      "Kültürel Unsurlar": "Farklı ülkelerden insanların yemekleri, giyim tarzları, müzikleri ve bayramları gibi kültürel farklılıklarına saygı duymanın önemini kavrarız."
    },
    "İngilizce": {
      "CLASSROOM RULES": "Sınıf içinde İngilizce olarak nasıl izin isteyeceğimizi ve ricada bulunacağımızı öğreneceğiz.",
      "Naming numbers (Numbers 1-50)": "1'den 50'ye kadar olan sayıları İngilizce olarak saymayı, okumayı ve yazmayı öğreniriz.",
      "Asking for permission (Can I ...? / May I ...?)": "Sınıfta kibarca izin isteyelim: 'Can I open the window, please?' (Pencereyi açabilir miyim, lütfen?). 'May I go to the toilet?' (Tuvalete gidebilir miyim?).",
      "Making simple requests (Imperatives - 1)": "Kibar bir şekilde ricada bulunmayı öğreniriz. 'Give me the book, please.' (Kitabı ver, lütfen).",
      "Telling someone what to do (Imperatives - 2)": "Basit komutlar vermeyi ve anlamayı pekiştiririz. 'Clean the board, please.' (Tahtayı temizle, lütfen).",
      "NATIONALITY": "Farklı ülkeleri ve milletleri İngilizce olarak ifade etmeyi ve birinin nereli olduğunu sormayı öğreneceğiz.",
      "Identifying countries and nationalities (Countries and Nationalities)": "Ülke (Turkey) ve milliyet (Turkish) arasındaki farkı öğreniriz. 'Germany' (Almanya) - 'German' (Alman) gibi.",
      "Making simple inquiries (Where are you from?)": "Birinin nereli olduğunu sormak için 'Where are you from?' kalıbını kullanırız. Cevap olarak 'I am from Turkey' deriz.",
      "Talking about locations of cities (Where is ...?)": "Bir şehrin nerede olduğunu sormayı öğreniriz. 'Where is Ankara?' (Ankara nerede?). Cevap: 'It is in Turkey.' (O Türkiye'de).",
      "CARTOON CHARACTERS": "Çizgi film karakterlerini kullanarak yeteneklerimizi ve sahip olduğumuz şeyleri ifade etmeyi öğreneceğiz.",
      "Expressing ability and inability - 1 (Can / Can't)": "Yapabildiğimiz (can) ve yapamadığımız (can't) eylemleri ifade ederiz. 'Superman can fly.' (Süpermen uçabilir). 'I can't fly.' (Ben uçamam).",
      "Expressing ability and inability - 2 (Can you ...?)": "Birinin bir şeyi yapıp yapamadığını sormayı öğreniriz. 'Can you swim?' (Yüzebilir misin?). Cevap: 'Yes, I can' veya 'No, I can't'.",
      "Talking about possessions (Possessive adjectives)": "Sahiplik sıfatlarını (my, your, his, her) kullanarak bir şeyin kime ait olduğunu belirtiriz. 'This is his car.' (Bu onun arabası).",
      "FREE TIME": "Boş zamanlarımızda yaptığımız aktiviteleri ve neleri sevip sevmediğimizi İngilizce olarak anlatmayı öğreneceğiz.",
      "Expressing likes and dislikes (Like / Dislike)": "Sevdiğimiz ve sevmediğimiz aktiviteleri ifade ederiz. 'I like playing football.' (Futbol oynamayı severim). 'I dislike doing homework.' (Ödev yapmayı sevmem).",
      "Making simple inquiries (Do you like ...?)": "Birinin bir aktiviteyi sevip sevmediğini sormayı öğreniriz. 'Do you like reading books?' (Kitap okumayı sever misin?).",
      "Asking for clarification (Asking for clarification)": "Birinin söylediğini anlamadığımızda tekrar etmesini istemek için 'Can you say that again, please?' (Tekrar söyler misin, lütfen?) gibi ifadeler kullanırız.",
      "MY DAY": "Günlük rutinlerimizi basit zaman kullanarak anlatmayı ve saati söylemeyi öğreneceğiz.",
      "Talking about daily routines (Simple Present Tense)": "Her gün yaptığımız işleri anlatırız. 'I wake up at 7 o'clock.' (Saat 7'de uyanırım). 'I go to school.' (Okula giderim).",
      "Making simple inquiries (Questions in Simple Present)": "Birinin günlük rutinleri hakkında sorular sorarız. 'What time do you wake up?' (Saat kaçta uyanırsın?). 'Do you go to school by bus?' (Okula otobüsle mi gidersin?).",
      "Telling the time and days (Time and days of the week)": "Saati ('It's three o'clock') ve haftanın günlerini ('Monday', 'Tuesday'...) söylemeyi öğreniriz.",
      "FUN WITH SCIENCE": "Basit bilimsel deneyler yaparken kullanabileceğimiz İngilizce komutları ve ifadeleri öğreneceğiz.",
      "Giving and responding to simple instructions - 1 (Vocabulary)": "Deneyle ilgili kelimeleri öğreniriz: 'water' (su), 'mix' (karıştırmak), 'pour' (dökmek), 'glass' (bardak) gibi.",
      "Giving and responding to simple instructions - 2 (Imperatives)": "Deney adımlarını anlatan komutları anlar ve uygularız. 'Pour the water into the glass.' (Suyu bardağın içine dök).",
      "Making simple inquiries (What is ...?)": "Deney sırasında nesnelerin ne olduğunu sorarız. 'What is this?' (Bu ne?). Cevap: 'It is a magnet.' (O bir mıknatıs).",
      "Talking about locations (Prepositions)": "Deneydeki nesnelerin yerini söyleriz. 'The magnet is in the box.' (Mıknatıs kutunun içinde).",
      "JOBS": "Farklı meslekleri ve bu meslekleri yapan kişilerin ne iş yaptıklarını İngilizce olarak anlatmayı öğreneceğiz.",
      "Describing what people do regularly (Jobs)": "Meslekleri ve görevlerini öğreniriz. 'A doctor helps sick people.' (Doktor hasta insanlara yardım eder). 'A teacher teaches students.' (Öğretmen öğrencilere öğretir).",
      "Making simple inquiries (Where do you work?)": "Birinin nerede çalıştığını sorarız. 'Where does a doctor work?' (Bir doktor nerede çalışır?). Cevap: 'He works at a hospital.' (O bir hastanede çalışır).",
      "MY CLOTHES": "Giysilerin isimlerini, hava durumunu ve mevsimleri öğrenerek hangi havada ne giyeceğimizi anlatacağız.",
      "Clothes": "Giysilerin İngilizce isimlerini öğreniriz: 't-shirt' (tişört), 'trousers' (pantolon), 'dress' (elbise), 'shoes' (ayakkabı) gibi.",
      "Describing the weather - 1 (Weather conditions)": "Hava durumunu ifade eden sıfatları öğreniriz: 'sunny' (güneşli), 'rainy' (yağmurlu), 'snowy' (karlı), 'windy' (rüzgarlı).",
      "Describing the weather - 2 (What's the weather like?)": "Hava durumunu sormayı öğreniriz. 'What's the weather like today?' (Bugün hava nasıl?). Cevap: 'It is sunny and hot.' (Hava güneşli ve sıcak).",
      "Expressing basic needs (Needs)": "Temel ihtiyaçlarımızı ifade ederiz. 'I need my coat.' (Montuma ihtiyacım var). 'I need an umbrella.' (Bir şemsiyeye ihtiyacım var).",
      "Making simple requests (May I ...? / Can I ...?)": "Birinden kibarca bir şey istemeyi öğreniriz. 'Can I wear my boots?' (Botlarımı giyebilir miyim?).",
      "Naming the seasons of the year (Seasons)": "Mevsimlerin İngilizce isimlerini öğreniriz: 'spring' (ilkbahar), 'summer' (yaz), 'autumn' (sonbahar), 'winter' (kış).",
      "MY FRIENDS": "Arkadaşlarımızın dış görünüşünü ve sahip oldukları şeyleri basit sıfatlar kullanarak anlatmayı öğreneceğiz.",
      "Describing people (Descriptions)": "İnsanları tarif eden sıfatları öğreniriz: 'tall' (uzun), 'short' (kısa), 'young' (genç), 'old' (yaşlı), 'beautiful' (güzel).",
      "Making simple inquiries (What is he like?)": "Birinin nasıl göründüğünü veya karakterini sorarız. 'What is he like?' Cevap: 'He is tall and funny.' (O uzun boylu ve komik).",
      "Talking about possessions (Have got / Has got)": "Sahip olduğumuz şeyleri anlatmak için 'have got' ve 'has got' kullanırız. 'I have got blue eyes.' (Mavi gözlerim var). 'She has got long hair.' (Onun uzun saçları var).",
      "FOOD AND DRINKS": "Yiyecek ve içeceklerin isimlerini, bir şeyler teklif etmeyi ve temel hislerimizi (açlık gibi) ifade etmeyi öğreneceğiz.",
      "Making offers - 1 (Offers)": "Birine bir şey ikram etmeyi öğreniriz. 'Would you like some cake?' (Biraz kek ister misin?). Cevap: 'Yes, please.' veya 'No, thanks.'",
      "Making offers - 2 (Requests)": "Birinden bir şey istemeyi öğreniriz. 'Can I have some water, please?' (Biraz su alabilir miyim, lütfen?).",
      "Expressing basic needs and feelings - 1 (Foods)": "Yiyecek ve içeceklerin isimlerini öğreniriz: 'pizza', 'hamburger', 'milk' (süt), 'juice' (meyve suyu) gibi.",
      "Expressing basic needs and feelings - 2 (Feelings)": "Açlık ve susuzluk gibi temel hislerimizi ifade ederiz. 'I am hungry.' (Açım). 'I am thirsty.' (Susadım).",
      "Making simple inquiries (Are you hungry?)": "Birinin aç olup olmadığını sorarız. 'Are you hungry?' (Aç mısın?). Cevap: 'Yes, I am' veya 'No, I am not'."
    },
    "Din Kültürü ve Ahlak Bilgisi": {
      "GÜNLÜK HAYATTAKİ DİNÎ İFADELER": "Günlük konuşmalarımızda kullandığımız ve kültürel mirasımızın bir parçası olan dinî ifadelerin anlamlarını öğreneceğiz.",
      "Günlük Hayattaki Dinî İfadeler": "Günlük hayatta bazı ifadeler kullanırız. Yemeğe başlarken 'Bismillah', güzel bir şey gördüğümüzde 'Maşallah', bir işi yapmayı umduğumuzda 'İnşallah', birine teşekkür ederken 'Allah razı olsun' deriz.",
      "Tekbir ve Salavat": "Tekbir'in ('Allâhü ekber') ve Salavat'ın ('Allahümme salli alâ Muhammed') ne anlama geldiğini ve nerelerde okunduğunu öğreniriz.",
      "Sübhâneke Duası ve Anlamı": "Sübhaneke duasını ve anlamını öğrenerek namazın hazırlık aşamasını kavramış oluruz.",
      "İSLAM'I TANIYALIM": "İslam dininin temel inanç esaslarını ve şartlarını öğreneceğiz.",
      "İslam'ın İnanç Esasları": "İmanın şartları olarak da bilinen Allah'a, meleklerine, kitaplarına, peygamberlerine, ahiret gününe, kaza ve kadere imanı öğreniriz.",
      "İslam'ın Şartları": "İslam'ın beş şartı vardır: Kelime-i Şehadet getirmek, Namaz kılmak, Oruç tutmak, Zekât vermek ve Hacca gitmek. Bunları elimizin beş parmağı gibi düşünebiliriz.",
      "Kur'an-ı Kerim'in İç Düzeni": "Kutsal kitabımız Kur'an-ı Kerim'in ayet, sure ve cüz gibi bölümlerden oluştuğunu öğreniriz.",
      "Âmentü Duası ve Anlamı": "İmanın şartlarını içinde barındıran Amentü duasını ve anlamını öğreniriz.",
      "GÜZEL AHLAK": "İyi bir insan olmanın gerektirdiği sevgi, saygı, dürüstlük gibi erdemleri ve Fatiha suresinin anlamını öğreneceğiz.",
      "Güzel Ahlak": "İyi bir insan olmanın gerektirdiği dürüstlük, yardımseverlik, merhamet, adalet gibi güzel davranışlardır.",
      "Sevgi ve Saygı": "Ailemize, arkadaşlarımıza, öğretmenlerimize ve tüm canlılara karşı sevgi ve saygı göstermenin önemini kavrarız.",
      "Fâtiha Suresi ve Anlamı": "Kur'an-ı Kerim'in ilk suresi olan Fatiha'yı ve onun genel anlamını öğreniriz.",
      "HZ. MUHAMMED'İ TANIYALIM": "Peygamberimiz Hz. Muhammed'in hayatını, ailesini ve örnek kişiliğini öğreneceğiz.",
      "Hz. Muhammed'in Doğduğu Çevreyi Tanıyalım": "Peygamberimizin doğduğu Mekke şehrinin o dönemdeki sosyal ve kültürel yapısı hakkında bilgi ediniriz.",
      "Hz. Muhammed'in Aile Büyüklerini Tanıyalım": "Peygamberimizin annesi Amine, babası Abdullah, dedesi Abdülmuttalip ve amcası Ebu Talip gibi aile büyüklerini tanırız.",
      "Hz. Muhammed'in Doğumu, Çocukluk ve Gençlik Yılları": "Peygamberimizin doğumu, çocukluğu, gençliğinde dürüstlüğü nedeniyle 'Muhammedü'l-Emin' (Güvenilir Muhammed) olarak anılmasını öğreniriz.",
      "Hz. Muhammed'in Mekke ve Medine Yılları": "Peygamberimizin İslam dinini tebliğ ettiği Mekke dönemi ve Müslümanlarla birlikte hicret ettiği Medine'deki yaşamı hakkında bilgi ediniriz.",
      "Salli ve Barik Duaları ve Anlamları": "Namazda okunan Salli ve Barik dualarını ve anlamlarını öğrenerek Peygamberimize olan sevgimizi ve saygımızı ifade ederiz.",
      "DİN VE TEMİZLİK": "Dinimizin temizliğe verdiği önemi, maddi ve manevi temizliğin ne anlama geldiğini öğreneceğiz.",
      "Dinim Temiz Olmamı İstiyor": "İslam dininin hem beden (abdest, gusül), hem elbise hem de çevre temizliğine çok büyük önem verdiğini ayet ve hadislerle öğreniriz.",
      "Bedenimi ve Elbiselerimi Temiz Tutarım": "Kişisel hijyenin (el, yüz, diş temizliği) ve giysilerimizi temiz tutmanın hem sağlık hem de dinî bir gereklilik olduğunu kavrarız."
    }
  }
} as const;
 